// anchorCreate.js — V4-ANCHORBASE-001, the CREATE half of the derivation.
//
// ─────────────────────────────────────────────────────────────────────────────────────────────────
// THE DEFECT THIS CLOSES
//
// public.plant_anchor_derivation was populated ONCE, by migrations/v4-anchorbase-001/0b-backfill.sql
// on 2026-08-12, and nothing has written a derivation since. deriveAnchor() in
// lambda/harvests/anchorDerive.js — the authored logic — had ZERO runtime callers in any Lambda; its
// only importer was scripts/measure-anchor-coverage.mjs, an offline measurement. So a planting
// created AFTER the backfill got no derived anchor at all, and lambda/harvests/watch.js dropped it
// from the harvest watch band with no_anchor forever.
//
// Confirmed read-only against live prod 2026-08-16, which is what makes this a defect rather than a
// theory: of the three anchorless live plantings created since the backfill, two hold NO derivation
// (Hydrangeas 2026-08-13, Super Sweet 100 Rescue 2026-08-12) and the third (Speckled Roman Rescue)
// only has one because the backfill itself caught it. Note that BOTH uncovered rows are
// PROJECT-LESS — 0b INNER JOINs plant_projects, so re-running it would not rescue them either.
//
// ─────────────────────────────────────────────────────────────────────────────────────────────────
// WHY THIS IS SQL AND NOT AN IMPORT OF deriveAnchor()
//
// Not a style choice — the import is undeployable. Each Lambda is zipped from its own directory
// (.github/workflows/deploy-lambda.yml: cd lambda/<fn> && zip -r), so an import of
// ../harvests/anchorDerive.js resolves under vitest, which inlines and dedupes, and then 502s at
// module load in the deployed function. lambda/plants/validate.js's header states the same rule, and
// anchorDerive.js additionally imports lambda/harvests/watch.js, so the copies-sync route would mean
// byte-mirroring a second, actively-evolving ~600-line module into this directory.
//
// So the same shape every OTHER writer of this relation already uses: the statement is written here,
// and lambda/plants/anchor-create.test.js is the drift guard. That guard does NOT compare SQL text —
// it IMPORTS the vocabulary from lambda/harvests/anchorDerive.js (ANCHOR_DERIVE_MODEL_VERSION,
// ADD_DATE_OFFSET_DAYS, DERIVATION_TIERS, OBSERVED_ANCHOR_FIELDS) and asserts the constants below
// equal it. anchorDerive.js therefore stays the canonical owner of the tier vocabulary even though
// nothing imports it at runtime; changing a tier's source, field, confidence or the offset there
// reds this Lambda's tests.
//
// ─────────────────────────────────────────────────────────────────────────────────────────────────
// ONLY TIER 3 CAN FIRE HERE, AND THAT IS STRUCTURAL RATHER THAN A SIMPLIFICATION
//
// deriveAnchor()'s precedence is sow event -> transplant event -> nursery proxy -> add-date
// baseline. The first three all read event_log rows keyed to plant_id. This statement runs against a
// planting whose id was generated by the INSERT that just returned, so NO event row can exist
// against it yet: tiers 1, 2 and 2.5 are empty by construction, not by omission, and evaluating them
// would be a join that provably returns nothing. The tier ORDER is still respected — the floor is
// reached because everything above it is absent.
//
// The consequence, stated rather than discovered later: an event logged AFTER the create does not
// upgrade this row. A transplant is self-healing (lambda/events/index.js writes transplanted_at and
// retires the derivation in the same transaction), but a sowing / seed_soak / potting_up logged
// later leaves a tier-3 guess live where tier 1 or 2.5 evidence now exists. That is a re-derivation
// pass — the nightly sweep in lambda/daily-plan is where it belongs — and it is NOT this change.
//
// ─────────────────────────────────────────────────────────────────────────────────────────────────
// WHAT THE CLAMP MEANS FOR A ROW WRITTEN AT CREATE TIME
//
// mark() in anchorDerive.js clamps a future anchor to today, because an anchor after today says the
// planting has not started. At create time add_date IS today, so add_date + 7 is ALWAYS in the
// future and the clamp ALWAYS binds: every row this writes lands at today, clamped_to_today = true,
// which is the same value 0b wrote for Speckled Roman Rescue (added 2026-08-12, derived the same
// day). The formula is written out rather than collapsed to the constant so it cannot silently
// disagree with 0b if a create is ever backdated.
//
// The honest cost: the row is frozen at derivation time, so a week later it reads 7 days EARLIER
// than the same planting would have derived under a later backfill run. The error is conservative
// (an early anchor opens a watch window early, it does not hide one) and it is visible — derived_on
// and clamped_to_today are both stored, so a later re-derivation pass can find exactly these rows.
//
// ─────────────────────────────────────────────────────────────────────────────────────────────────
// TWO DELIBERATE DIVERGENCES FROM 0b, both narrowing rather than widening what gets written
//
//   * OWNERSHIP IS TWO-ARM. 0b takes user_id from plant_projects.created_by via an INNER JOIN, which
//     silently excludes every project-less planting — and both live uncovered rows above are exactly
//     that. This uses COALESCE(container.created_by, planting.created_by), the same two-arm shape
//     BUG-STATUSADVNOPROJ-001 / BUG-ANCHORNOPROJ-001 put on the transplant write and the watch
//     route. Project-owner attribution is still preferred where a project exists (consult 2026-08-12
//     decision 1 item 4: 13 live plantings carry a data-import pseudo-user as plants.created_by).
//   * PLAUSIBILITY STAMPS rescue_suspect ONLY. 0b also stamps post_frost_impossible, which needs a
//     first-fall-frost anchor and a catalogue DTM; this Lambda has neither, and inventing a frost
//     date here would be a second, disagreeing copy of one. It is not a gap in coverage: the
//     consumer already suppresses that class at READ time — lambda/harvests/watch.js condition 3
//     compares the date the watch would OPEN against firstFallFrostFor(etToday) and drops the row.
//     The plausibility vocabulary is a CHECK constraint, so a third value would be a migration, and
//     an unapplied CHECK value written by a deployed Lambda is a 23514 on every create.

// Tier 3 of DERIVATION_TIERS, restated locally because the module cannot be imported at runtime.
// anchor-create.test.js asserts each of these against lambda/harvests/anchorDerive.js's exports.
const SOURCE = 'add_date_baseline';
const CONFIDENCE = 'baseline';
const ANCHOR_FIELD = 'transplanted_at';
const MODEL_VERSION = 'anchor-derive-v1';

// Dave's stated baseline (BD0806-27). ALWAYS the constant, never the household median: 0b's header
// records the measured reversal (offset sweep over 112 dual-dated plantings, +7 hits 68.8% within a
// week, the median +9 hits 46.4%), so offset_source is 'stated_baseline' by decision, not by
// fallback. offset_sample_n is still recorded for provenance — it says how much dual-dated data the
// household held when the choice was made, and is the reason the count subquery below exists at all.
const OFFSET_DAYS = 7;
const OFFSET_SOURCE = 'stated_baseline';

// 0b's "live" definition, mirrored so a planting created directly into a dead status is not derived
// for. Everything else 0b filters (deleted, archived) is trivially false on a row that was just
// inserted; those predicates are kept anyway so a re-run of this statement behaves like 0b.
const DEAD_STATUSES = ['failed', 'ended', 'dormant'];

// Derive the anchor a just-created planting has no evidence for.
//
// ONE statement, ONE relation written (public.plant_anchor_derivation) — public.plants is READ and
// never touched, so none of its four row-level UPDATE triggers fire and no planting's updated_at or
// version moves. That is the same guarantee 0c check 6 proves for the backfill.
//
// EMITTED UNCONDITIONALLY, not behind a JS test of the returned row, for the reason the plants PUT
// states at its own retire: the predicate belongs in SQL where it is evaluated against the row that
// was actually written. A JS gate mirrored from the INSERT body is one edit to the column list away
// from disagreeing with it. The cost of always sending it is one probe of the primary key.
//
// Returns the inserted row, or null when the statement correctly wrote nothing (the planting already
// carries an observed date, it is in a dead status, or a live derivation already exists).
export async function deriveAnchorOnCreate(sql, plantId) {
  if (plantId == null) return null;
  const rows = await sql`
    INSERT INTO public.plant_anchor_derivation
      (user_id, plant_id, anchor_date, anchor_field, source, confidence, model_version,
       evidence_date, offset_days, offset_source, offset_sample_n, clamped_to_today, derived_on,
       plausibility)
    SELECT COALESCE(c.created_by, gp.created_by),
           gp.id,
           LEAST(dts.add_date + ${OFFSET_DAYS}::int, dts.et_today),
           ${ANCHOR_FIELD}::text,
           ${SOURCE}::text,
           ${CONFIDENCE}::text,
           ${MODEL_VERSION}::text,
           dts.add_date,
           ${OFFSET_DAYS}::int,
           ${OFFSET_SOURCE}::text,
           (SELECT count(*)::int
              FROM public.garden_node dgp
              JOIN public.container dc ON dc.id = dgp.container_id
             WHERE dc.created_by = COALESCE(c.created_by, gp.created_by)
               AND dgp.deleted_at IS NULL
               AND dc.deleted_at IS NULL
               AND dgp.transplanted_at IS NOT NULL),
           (dts.add_date + ${OFFSET_DAYS}::int) > dts.et_today,
           dts.et_today,
           CASE WHEN gp.display_name ILIKE '%rescue%'
                  OR gp.status IN ('flowering', 'fruiting') THEN 'rescue_suspect'
                ELSE NULL END
      FROM public.garden_node gp
      LEFT JOIN public.container c ON c.id = gp.container_id
      CROSS JOIN LATERAL (
        SELECT (gp.created_at AT TIME ZONE 'America/New_York')::date AS add_date,
               (now()         AT TIME ZONE 'America/New_York')::date AS et_today
      ) dts
     WHERE gp.id = ${plantId}::uuid
       AND gp.deleted_at IS NULL
       AND gp.archived_at IS NULL
       AND (gp.status IS NULL OR NOT (gp.status = ANY(${DEAD_STATUSES}::text[])))
       AND gp.sown_at IS NULL
       AND gp.transplanted_at IS NULL
       AND gp.planted_out_at IS NULL
       AND NOT EXISTS (
             SELECT 1 FROM public.plant_anchor_derivation x
              WHERE x.plant_id = gp.id
                AND x.superseded_at IS NULL)
    RETURNING id, plant_id, user_id, anchor_date, anchor_field, source, confidence,
              model_version, evidence_date, offset_days, offset_source, offset_sample_n,
              clamped_to_today, derived_on, plausibility
  `;
  return rows?.[0] ?? null;
}
