-- 0p-post-deploy-backfill.sql
-- schema_version: 5.0.0-putupmake-001-backfill
--
-- V5-PUTUPMAKE-001 — the use_by_basis backfill. POST-DEPLOY ONLY. Every existing jar gets the basis
--   its discard-by date already has; no date is changed, added or removed.
--
-- ⚠ WHEN: only after verify-deploy shows B's Lambda live (preservation function CodeSha256 = the
--   promoted build) — 05-release-train §3 step 12, first of the post-deploy steps: this backfill ->
--   pesto re-file -> zucchini fix -> recipe seed (after Dave has seen the list) -> staged-promote clear.
--   WHY NOT EARLIER: 0a leaves use_by_basis NULL on every row, which keeps the basis/date CHECK
--   vacuous for release 1a's writer. Once a row carries a basis, 1a's date Edit on it can 23514 (a
--   'none' row given a date). So this runs when 1a's Lambda is gone, never before — and it is also
--   what ends 0r's window (0r refuses once any basis is set).
--
-- REFUSES unless 0a's stamp ('5.0.0-putupmake-001') is on this database. IDEMPOTENT: it only ever
--   touches rows WHERE use_by_basis IS NULL, so a re-run changes nothing B's writers have set, and its
--   own stamp is ON CONFLICT DO NOTHING. gates.yml's NULL-basis gate is keyed on THIS file's stamp
--   ('5.0.0-putupmake-001-backfill'), not on 0a's, so pushing the migration directory never reds a
--   database the backfill has not reached yet.
--
-- THE SPLIT (V4, data model for release 1b — exhaustive; every NULL-basis row lands in exactly one):
--   * no date, and a frozen matrix has no figure for (method, kind)   -> none
--   * no date, and both frozen matrices have a figure                 -> typed (his "No expiry")
--   * a date equal to preserved_at + a frozen figure for (method, kind) -> table (candy: house)
--   * any other date                                                  -> typed
--   "kind" is the row's place kind, or 'unrecorded' when the row has no place. A figure counts whether
--   it came from an explicit leg or from the engine's fallthrough default — the matrices already hold
--   the resolved number per cell. The month arithmetic is Postgres date + interval, which clamps to
--   the last day of a short month exactly as the engine's writer does.
--   WHY "EITHER MATRIX": a row may have been written before release 1a or under it, and nothing on
--   the row says which. So a date or a missing date that EITHER engine could have produced is
--   attributed to the engine (table, or none), and only what NEITHER could have produced is
--   attributed to the cook (typed). The only cells where the two answers differ are the eleven 1a
--   fridge cells, and no fridge place existed on prod when this was written.
--
-- THE MATRICES ARE FROZEN LITERALS, NEVER THE LIVE ENGINE (05 §6, review3). B's Lambda carries the
--   1b..4 engine, whose cells differ; importing it would silently compare against the wrong table.
--   * before_1a — the engine as shipped before release 1a: BEFORE_1A in
--     lambda/preservation/shelfLife.test.js, pinned in 245042883464dd23d518e82b3fe16bf77964c553
--     (lane-putup1a-server-20260929), generated by running the engine at garden-app dev
--     45fa81417425febcad5f12ad4b88014c0ae944fc.
--   * after_1a — release 1a's matrix: AFTER_1A in the same file at
--     4e8846587c3f3e2314a376dd355ef7f3a47b31dd (same lane), which is before_1a with exactly the eleven
--     fridge cells of the V4 decisions list, item 6 (the 1a bullet), set to no date. Unchanged
--     through lane HEAD 3d9e83d8b41182855907182adbb972140c46ca15.
--   ⚠ If release 1a's AFTER_1A changes before promote A ships, re-freeze after_1a from the SHIPPED
--   commit before this file's first apply. The self-check below (section 1) refuses a matrix pair that
--   does not differ in exactly those eleven cells.
--   Columns, in the literal's order: deep_freezer, fridge_freezer, fridge, pantry, cold_storage, other,
--   unrecorded. NULL = no figure (no date).
--
-- LIVE ROWS, measured read-only on prod 2026-09-29 (5 rows, all in deep-freezer places): 2
--   whole_freeze and 2 passata dated preserved_at + 12 months -> table; 1 'other' with no date -> none.
--
-- AUDIT: use_by_basis is a watched column, so every row updated here writes an audit_events row. The
--   actor is set to this file's stamp rather than left as 'system'. updated_at moves on every
--   backfilled row (set_updated_at): the row did change — it gained a basis.

BEGIN;

SET LOCAL lock_timeout = '5s';

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public.schema_version WHERE version = '5.0.0-putupmake-001') THEN
    RAISE EXCEPTION 'v5-putupmake-001 0p refused: 0a (5.0.0-putupmake-001) is not applied to this database';
  END IF;
END $$;

SELECT set_config('app.actor_clerk_sub', 'migration:5.0.0-putupmake-001-backfill', true);

-- ── 1. The frozen matrices ───────────────────────────────────────────────────────────────────────
CREATE TEMP TABLE putupmake_frozen_matrix (
  matrix         text NOT NULL,
  method         text NOT NULL,
  deep_freezer   integer,
  fridge_freezer integer,
  fridge         integer,
  pantry         integer,
  cold_storage   integer,
  other          integer,
  unrecorded     integer,
  PRIMARY KEY (matrix, method)
) ON COMMIT DROP;

INSERT INTO putupmake_frozen_matrix VALUES
  --                                  deep  f_frz fridge pantry cold other unrec
  ('before_1a', 'roast_freeze',        12,   4,   10,    10,    10,  10,   10),
  ('before_1a', 'whole_freeze',        12,   4,   10,    10,    10,  10,   10),
  ('before_1a', 'blanch_freeze',       12,   4,   10,    10,    10,  10,   10),
  ('before_1a', 'dehydrate',            4,   4,    4,     4,     6,   4,    4),
  ('before_1a', 'powder',               4,   4,    4,     4,     6,   4,    4),
  ('before_1a', 'passata',             12,  12,   12,    12,    18,  12,   12),
  ('before_1a', 'can_water_bath',      12,  12,   12,    12,    18,  12,   12),
  ('before_1a', 'can_pressure',        12,  12,   12,    12,    12,  12,   12),
  ('before_1a', 'jam_preserve',        12,  12,   12,    12,    18,  12,   12),
  ('before_1a', 'ferment',              6,   6,    6,     6,     8,   6,    6),
  ('before_1a', 'cure_store',           3,   3,    3,     3,     4,   3,    3),
  ('before_1a', 'cold_store',           4,   4,    4,     4,     6,   4,    4),
  ('before_1a', 'purchased_preserved', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('before_1a', 'quick_pickle',        12,   4,    2,    12,    12,   2,    2),
  ('before_1a', 'pesto',               12,   4,   10,    10,    10,  10,   10),
  ('before_1a', 'hot_sauce',            6,   6,    6,    12,    18,   6,    6),
  ('before_1a', 'ferment_mash',         6,   6,    6,     6,     8,   6,    6),
  ('before_1a', 'candy',                6,   4,    1,     1,     1,   1,    1),
  ('before_1a', 'other',               NULL, NULL, NULL, NULL, NULL, NULL, NULL),

  ('after_1a',  'roast_freeze',        12,   4,  NULL,   10,    10,  10,   10),
  ('after_1a',  'whole_freeze',        12,   4,  NULL,   10,    10,  10,   10),
  ('after_1a',  'blanch_freeze',       12,   4,  NULL,   10,    10,  10,   10),
  ('after_1a',  'dehydrate',            4,   4,  NULL,    4,     6,   4,    4),
  ('after_1a',  'powder',               4,   4,  NULL,    4,     6,   4,    4),
  ('after_1a',  'passata',             12,  12,  NULL,   12,    18,  12,   12),
  ('after_1a',  'can_water_bath',      12,  12,  NULL,   12,    18,  12,   12),
  ('after_1a',  'can_pressure',        12,  12,  NULL,   12,    12,  12,   12),
  ('after_1a',  'jam_preserve',        12,  12,  NULL,   12,    18,  12,   12),
  ('after_1a',  'ferment',              6,   6,    6,     6,     8,   6,    6),
  ('after_1a',  'cure_store',           3,   3,  NULL,    3,     4,   3,    3),
  ('after_1a',  'cold_store',           4,   4,    4,     4,     6,   4,    4),
  ('after_1a',  'purchased_preserved', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
  ('after_1a',  'quick_pickle',        12,   4,    2,    12,    12,   2,    2),
  ('after_1a',  'pesto',               12,   4,  NULL,   10,    10,  10,   10),
  ('after_1a',  'hot_sauce',            6,   6,    6,    12,    18,   6,    6),
  ('after_1a',  'ferment_mash',         6,   6,    6,     6,     8,   6,    6),
  ('after_1a',  'candy',                6,   4,    1,     1,     1,   1,    1),
  ('after_1a',  'other',               NULL, NULL, NULL, NULL, NULL, NULL, NULL);

-- One row per (matrix, method, kind); months NULL = no figure.
CREATE TEMP VIEW putupmake_frozen_cell AS
  SELECT f.matrix, f.method, k.kind, k.months
    FROM putupmake_frozen_matrix f
   CROSS JOIN LATERAL (VALUES ('deep_freezer', f.deep_freezer), ('fridge_freezer', f.fridge_freezer),
                              ('fridge', f.fridge), ('pantry', f.pantry),
                              ('cold_storage', f.cold_storage), ('other', f.other),
                              ('unrecorded', f.unrecorded)) AS k(kind, months);

-- Self-check, so a transcription slip in either literal is loud: both matrices cover exactly the
-- methods the live method CHECK admits, and they differ in exactly the eleven disclosed fridge cells,
-- each a figure before 1a and no date after it.
DO $$
DECLARE
  v_diff   text;
  v_live   text;
  v_frozen text;
BEGIN
  SELECT string_agg(m, ',' ORDER BY m COLLATE "C") INTO v_live
    FROM (SELECT DISTINCT (regexp_matches(pg_get_constraintdef(c.oid), '''([a-z_]+)''', 'g'))[1] AS m
            FROM pg_constraint c
            JOIN pg_class t ON t.oid = c.conrelid
            JOIN pg_namespace n ON n.oid = t.relnamespace
           WHERE n.nspname = 'public' AND t.relname = 'preservation_log'
             AND c.conname = 'chk_preservation_log_method') s;
  FOR v_frozen IN
    SELECT string_agg(method, ',' ORDER BY method COLLATE "C") FROM putupmake_frozen_matrix GROUP BY matrix
  LOOP
    IF v_frozen IS DISTINCT FROM v_live THEN
      RAISE EXCEPTION 'v5-putupmake-001 0p refused: a frozen matrix covers methods [%], the live method CHECK admits [%]', v_frozen, v_live;
    END IF;
  END LOOP;

  SELECT string_agg(b.method || '/' || b.kind || ':' || COALESCE(b.months::text, '-') || '>'
                    || COALESCE(a.months::text, '-'), ',' ORDER BY b.method COLLATE "C", b.kind COLLATE "C") INTO v_diff
    FROM putupmake_frozen_cell b
    JOIN putupmake_frozen_cell a
      ON a.matrix = 'after_1a' AND a.method = b.method AND a.kind = b.kind
   WHERE b.matrix = 'before_1a' AND a.months IS DISTINCT FROM b.months;
  IF v_diff IS DISTINCT FROM
       'blanch_freeze/fridge:10>-,can_pressure/fridge:12>-,can_water_bath/fridge:12>-,'
       'cure_store/fridge:3>-,dehydrate/fridge:4>-,jam_preserve/fridge:12>-,passata/fridge:12>-,'
       'pesto/fridge:10>-,powder/fridge:4>-,roast_freeze/fridge:10>-,whole_freeze/fridge:10>-' THEN
    RAISE EXCEPTION 'v5-putupmake-001 0p refused: the frozen matrices differ in [%], not in exactly the eleven disclosed 1a fridge cells', v_diff;
  END IF;
END $$;

-- ── 2. The backfill ──────────────────────────────────────────────────────────────────────────────
WITH target AS (
  SELECT p.id, p.method, p.preserved_at, p.use_by_target,
         COALESCE(sl.kind, 'unrecorded') AS kind
    FROM public.preservation_log p
    LEFT JOIN public.storage_location sl ON sl.id = p.storage_location_id
   WHERE p.use_by_basis IS NULL
), decided AS (
  SELECT t.id,
         CASE
           WHEN t.use_by_target IS NULL THEN
             CASE WHEN EXISTS (SELECT 1 FROM putupmake_frozen_cell c
                                WHERE c.method = t.method AND c.kind = t.kind AND c.months IS NULL)
                       OR NOT EXISTS (SELECT 1 FROM putupmake_frozen_cell c
                                       WHERE c.method = t.method AND c.kind = t.kind)
                  THEN 'none'
                  ELSE 'typed'
             END
           WHEN EXISTS (SELECT 1 FROM putupmake_frozen_cell c
                         WHERE c.method = t.method AND c.kind = t.kind AND c.months IS NOT NULL
                           AND (t.preserved_at + make_interval(months => c.months))::date
                               = t.use_by_target)
             THEN CASE WHEN t.method = 'candy' THEN 'house' ELSE 'table' END
           ELSE 'typed'
         END AS basis
    FROM target t
)
UPDATE public.preservation_log p
   SET use_by_basis = d.basis
  FROM decided d
 WHERE p.id = d.id
   AND p.use_by_basis IS NULL;

-- What the backfill decided, for the operator's log (whole table, soft-deleted rows included).
SELECT use_by_basis, (use_by_target IS NOT NULL) AS dated, count(*) AS jars
  FROM public.preservation_log
 GROUP BY 1, 2
 ORDER BY 1, 2;

-- ── 3. The stamp. gates.yml's NULL-basis gate arms on it. ───────────────────────────────────────
INSERT INTO public.schema_version (version, description)
VALUES ('5.0.0-putupmake-001-backfill',
        'V5-PUTUPMAKE-001 post-deploy: use_by_basis backfilled on every row that had none (none / typed '
        '/ table, candy: house) against FROZEN copies of the pre-1a engine matrix '
        '(245042883464dd23d518e82b3fe16bf77964c553) and release 1a''s matrix '
        '(4e8846587c3f3e2314a376dd355ef7f3a47b31dd). No date changed. Arms the NULL-basis gate.')
ON CONFLICT (version) DO NOTHING;

COMMIT;
