-- 0c-arm.sql
-- V5-SEEDMULTIPARENT-001 — write the SECOND stamp, 5.0.0-seedmultiparent-001b, and only if the member
--   cache already holds on every row. That stamp is what the two row-level gates key on
--   (gates-rowlevel.yml.pending): written = "from here on, source_plant_id and the live seed_parent
--   rows must agree, forever".
--
-- ⚠ WHEN: only AFTER the Lambda release that writes the column and the rows together is LIVE on this
--   environment (inventory-items AND plants functions — verify-deploy, not the promote's say-so), and
--   after 0b-reconcile.sql has been run again behind it. NEVER straight after 0a. While the old Lambda
--   is live it writes the column only, so every parent Dave saves, changes or clears breaks the
--   invariant by design; a stamp written then certifies a state the deployed writer is about to undo.
--   This is the house rule for a writer-coupled constraint (gardening-deploy "arming a CHECK is NOT
--   backward-compatible", the 2026-08-03 outage) applied to a gate instead of a CHECK: the arming step
--   is its own file, post-deploy, and it refuses if any row would violate.
--
-- THE TWO INVARIANTS, exactly the two gates in gates-rowlevel.yml.pending, and together exactly the
--   member-cache rule (0a header D1). NEITHER filters on the lot's deleted_at — a soft-deleted lot keeps
--   its link rows and must come back consistent:
--     (i)  every inventory_items row with a non-NULL source_plant_id has a LIVE seed_parent row for
--          that plant                                          (the cache is a live member);
--     (ii) every lot with a live seed_parent row has a non-NULL source_plant_id
--                                                              (a non-empty set has a cache).
--
-- REFUSES (RAISE EXCEPTION, nothing written) when 0a is not applied here, or when either invariant
--   returns a row. The message carries both counts. What to do with a refusal:
--     * run 0b-reconcile.sql — it repairs every lot with at most one live row;
--     * if 0b's R3 list is not empty, those lots have two or more parents and a cache that is not one
--       of them. 0b will not touch them and neither does this. A person decides; do not edit this file
--       to get past it.
--
-- IDEMPOTENT: the stamp is ON CONFLICT DO NOTHING, so a re-run on an armed database re-checks both
--   invariants and changes nothing. A re-run that REFUSES on an armed database is a finding — the same
--   one the standing gates will report — not a reason to remove the stamp.
--
-- REVERSIBLE: DELETE the 001b row. That returns the two row-level gates to vacuous without touching a
--   row of data or the table. 0r-rollback.sql removes both stamps.
--
-- Usage: psql "$NEON_DATABASE_URL" -X -v ON_ERROR_STOP=1 -f 0c-arm.sql

BEGIN;

DO $$
DECLARE
  v_not_member bigint;
  v_no_cache   bigint;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public.schema_version WHERE version = '5.0.0-seedmultiparent-001') THEN
    RAISE EXCEPTION 'v5-seedmultiparent-001 0c refused: 0a (5.0.0-seedmultiparent-001) is not applied here. Nothing to arm.';
  END IF;

  -- (i) the cache is a live member.
  SELECT count(*) INTO v_not_member
    FROM public.inventory_items i
   WHERE i.source_plant_id IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM public.seed_lot_parent_planting l
                      WHERE l.inventory_item_id = i.id
                        AND l.plant_id = i.source_plant_id
                        AND l.role = 'seed_parent'
                        AND l.deleted_at IS NULL);

  -- (ii) a non-empty set has a cache.
  SELECT count(DISTINCT l.inventory_item_id) INTO v_no_cache
    FROM public.seed_lot_parent_planting l
    JOIN public.inventory_items i ON i.id = l.inventory_item_id
   WHERE l.role = 'seed_parent'
     AND l.deleted_at IS NULL
     AND i.source_plant_id IS NULL;

  IF v_not_member > 0 OR v_no_cache > 0 THEN
    RAISE EXCEPTION 'v5-seedmultiparent-001 0c refused, nothing written: % lot(s) whose source_plant_id is not one of their live seed_parent rows; % lot(s) with live seed_parent rows and a NULL source_plant_id.',
      v_not_member, v_no_cache
      USING HINT = 'Run 0b-reconcile.sql, then this file again. If 0b lists lots under R3, a person decides those; do not arm around them.';
  END IF;

  INSERT INTO public.schema_version (version, description)
  VALUES ('5.0.0-seedmultiparent-001b',
          'SEEDMULTIPARENT arm: V5-SEEDMULTIPARENT-001, post-deploy. Written by 0c-arm.sql only after '
          'the Lambda that writes inventory_items.source_plant_id and seed_lot_parent_planting in one '
          'transaction is live and 0b-reconcile.sql has run behind it, and only when both row-level '
          'invariants returned zero rows: (i) every lot with a non-NULL source_plant_id has a live '
          'seed_parent row for that plant; (ii) every lot with a live seed_parent row has a non-NULL '
          'source_plant_id. Neither filters on the lot''s deleted_at. Arms the two row-level gates '
          '(post_cache_is_a_live_member, post_nonempty_set_has_a_cache). Writes no data.')
  ON CONFLICT (version) DO NOTHING;
END $$;

-- What this database now carries. Two rows = armed.
SELECT version, applied_at
  FROM public.schema_version
 WHERE version IN ('5.0.0-seedmultiparent-001', '5.0.0-seedmultiparent-001b')
 ORDER BY version;

COMMIT;
