// BUG-WXBANNERSHOWERYCOPY-001 — real-browser check of the WeatherWidget caveat banner at phone width.
//
// The vitest suite (src/__tests__/wxBannerIncomplete.test.jsx) asserts the exact sentences; what it cannot
// show is the banner wrapping in a real layout at Dave's width. Frame it at a TRUE 390px with
// viewport.html?vw=390&page=wxbanner.html (a bare --window-size lays out at ~500px and crops).
// The three payloads are stored daily_plan.items.hydrology shapes GENERATED by the real engine +
// station code (generatePlan / mergeStationHydrology(null, …)) at lane-nextfixes-20260918, pasted
// verbatim: the lambda modules are CommonJS and cannot be imported into the browser.
import React, { useEffect, useState } from 'react'
import { createRoot } from 'react-dom/client'
import WeatherWidget from '../../src/components/today/WeatherWidget.jsx'

const weather = { tonightLow: 58, highToday: 78, code: 3, hot: false }
const GEN = '2026-07-06T10:00:00Z'
const DAY = '2026-07-06'

// Open-Meteo down, no gauge bound: engine.generatePlan with hydrology null.
const unbound = { status: { ok: false, uncertainty: { flag: true, reason: 'precip data incomplete — watering advice assumes no rain credit' } } }
// Open-Meteo down, fresh gauge (the 2026-09-02 shape): mergeStationHydrology(null, st) -> generatePlan, + handler's station bag.
const bound = { recent_precip_in: 0.5, today_precip_in: 0.01, today_pop: null, upcoming_precip_in: null, tomorrow_precip_in: null,
  tomorrow_pop: null, today_observed_in: 0.01, today_remaining_in: 0, rain_coming: false, rain_horizon: null,
  status: { ok: false, uncertainty: { flag: true, reason: 'precip data incomplete — watering advice still credits recent rain' } },
  station: { recent_source: 'station', today_remaining_basis: 'wholeday', today_remaining_fallback: 'no_hourly', today_source: 'station',
    yesterday_actual_source: 'station', station_age_min: 10, station_fresh: true, station_mac: 'AA:BB:CC:DD:EE:FF' } }
// A genuine showery day — the copy that must NOT change.
const showery = { recent_precip_in: 0.05, today_precip_in: 0.21, today_pop: 88, upcoming_precip_in: 0.95, tomorrow_precip_in: 0.74,
  tomorrow_pop: 63, rain_coming: true, rain_horizon: 'tomorrow',
  status: { ok: true, uncertainty: { flag: true, reason: 'showery today (88% on 0.21") — showery amounts shift through the day' } } }

const CASES = [
  ['forecast missing, no gauge', unbound],
  ['forecast missing, gauge bound (09-02 shape)', bound],
  ['genuine showery day (unchanged)', showery],
]

// Burned into the capture so the width is self-evidencing, not trusted.
function Badge() {
  const [t, setT] = useState('')
  useEffect(() => {
    const d = document.documentElement
    setT(`vw ${window.innerWidth} · scrollW ${d.scrollWidth} · hscroll ${d.scrollWidth > window.innerWidth ? 'YES' : 'no'}`)
  }, [])
  return <div id="badge">{t}</div>
}

createRoot(document.getElementById('root')).render(
  <>
    <Badge />
    {CASES.map(([label, hy]) => (
      <div key={label}><h2>{label}</h2><WeatherWidget weather={weather} hydrology={hy} generatedAt={GEN} planDate={DAY} /></div>
    ))}
  </>
)
