// BUG-WXOUTAGESTAMPCOPY-001 — real-browser check of the WeatherWidget stamp and gauge line at phone width.
//
// The vitest suite (src/__tests__/wxOutageStampCopy.test.jsx) asserts every line; what it cannot show is the
// card as Dave sees it. Frame it at a TRUE 390px with viewport.html?vw=390&page=wxoutage.html (a bare
// --window-size lays out at ~500px and crops). The four payloads are stored daily_plan.items.hydrology
// shapes GENERATED by the real engine + station code (generatePlan / mergeStationHydrology) at
// lane-outagecopy-20260918, pasted verbatim: the lambda modules are CommonJS and cannot be imported here.
import React, { useEffect, useState } from 'react'
import { createRoot } from 'react-dom/client'
import WeatherWidget from '../../src/components/today/WeatherWidget.jsx'

const weather = { tonightLow: 58, highToday: 78, code: 3, hot: false }
const GEN = '2026-07-06T10:00:00Z'
const DAY = '2026-07-06'

// Forecast fetch empty, no gauge bound: engine.generatePlan with hydrology null.
const unbound = { status: { ok: false, uncertainty: { flag: true, reason: 'precip data incomplete — watering advice assumes no rain credit' } } }
// Forecast fetch empty, fresh gauge (the 2026-09-02 shape): mergeStationHydrology(null, st) -> generatePlan, + handler's bag.
const bound = { recent_precip_in: 0.5, today_precip_in: 0.01, today_pop: null, upcoming_precip_in: null, tomorrow_precip_in: null,
  tomorrow_pop: null, today_observed_in: 0.01, today_remaining_in: 0, rain_coming: false, rain_horizon: null,
  status: { ok: false, uncertainty: { flag: true, reason: 'precip data incomplete — watering advice still credits recent rain' } },
  station: { recent_source: 'station', today_remaining_basis: 'wholeday', today_remaining_fallback: 'no_hourly', today_source: 'station',
    yesterday_actual_source: 'station', station_age_min: 10, station_fresh: true, station_mac: 'AA:BB:CC:DD:EE:FF' } }
// Forecast came through and its hourly block has no more rain today — "none more expected" is TRUE here and must stay.
const completeBound = { recent_precip_in: 0.5, today_precip_in: 0.01, today_pop: 40, upcoming_precip_in: 0.3, tomorrow_precip_in: 0.2,
  tomorrow_pop: 35, today_observed_in: 0.01, today_remaining_in: 0, rain_coming: false, rain_horizon: null,
  status: { ok: true, uncertainty: { flag: false } },
  station: { recent_source: 'station', today_remaining_basis: 'hourly', today_remaining_from_hour: 2, today_source: 'station',
    today_next_window_h: 3, yesterday_actual_source: 'station', station_age_min: 10, station_fresh: true, station_mac: 'AA:BB:CC:DD:EE:FF' } }
// Forecast came through, no gauge — the Open-Meteo stamp must stay.
const completeUnbound = { recent_precip_in: 0.05, today_precip_in: 0, today_pop: 10, upcoming_precip_in: 0.3, tomorrow_precip_in: 0.2,
  tomorrow_pop: 35, rain_coming: false, rain_horizon: null, status: { ok: true, uncertainty: { flag: false } } }

const CASES = [
  ['forecast missing, no gauge', unbound],
  ['forecast missing, gauge bound (09-02 shape)', bound],
  ['forecast complete, gauge bound (unchanged)', completeBound],
  ['forecast complete, no gauge (unchanged)', completeUnbound],
]

// Burned into the capture so the width is self-evidencing, not trusted.
function Badge() {
  const [t, setT] = useState('')
  useEffect(() => {
    const d = document.documentElement
    setT(`vw ${window.innerWidth} · scrollW ${d.scrollWidth} · hscroll ${d.scrollWidth > window.innerWidth ? 'YES' : 'no'}`)
  }, [])
  return <div id="badge">{t}</div>
}

createRoot(document.getElementById('root')).render(
  <>
    <Badge />
    {CASES.map(([label, hy]) => (
      <div key={label}><h2>{label}</h2><WeatherWidget weather={weather} hydrology={hy} generatedAt={GEN} planDate={DAY} /></div>
    ))}
  </>
)
