// Vocabulary fixture for the VoiceHarvest one-breath tests (V5-VOICEVOCAB-001, lane D4).
//
// THE REAL NAMES, NOT INVENTED ONES. These 244 rows are lane D2's snapshot of the ?view=picker population
// on prod, 2026-09-23 (garden-app 61c6f1fc2131a0751071f0d8ffdf381157c265da:src/__tests__/voiceCare.fixture.js,
// added in ac841b29b81820ff570621af974cc8388240aac9), reduced to the four fields a voice name matcher reads:
// planting name, variety name, crop slug, crop search_aliases. Status and location are dropped — nothing
// here reads them. Ids are synthetic and deterministic; there are no user ids.
//
// WHY THE WHOLE LIST. The hazard these tests exist for is a property of THIS vocabulary: thirteen
// plantings carry a digit or a number word in some alias (1884, Alaska Mix Nasturtium 1, Armageddon F1,
// Cherry Rescue 1, Chinese 5-Color, Clemson Spineless 80, Danvers 126, Fairway Orange Coleus Clone 1,
// Marvel of Four Seasons, Megatron F1, Peach tree, Super Sweet 100, Super Sweet 100 Rescue), and a bare
// "2" reaches Danvers 1*2*6 by substring. A hand-made handful would only prove the author could imagine
// the collisions. The data is frozen; live names will drift, so these tests pin behaviour on this
// snapshot, not facts about the garden today.
import { splitCropAliases } from '../lib/comboboxInput.js'

// [planting name, variety name, crop slug, crop search_aliases]
const ROWS = [
  ['1884', '1884', 'tomato', ''],
  ['Alaska Mix Nasturtium 1', 'Alaska Mix', 'nasturtium', ''],
  ['Aloe Vera', 'Aloe Vera', 'aloe', ''],
  ['Anaheim', 'Anaheim', 'pepper', ''],
  ['Ancho', 'Ancho', 'pepper', ''],
  ['Armageddon', 'Armageddon F1', 'pepper', ''],
  ['Arugula', 'Arugula', 'arugula', 'rocket'],
  ['Atomic Red Carrot', 'Atomic Red', 'carrot', ''],
  ['Australe Butterhead Lettuce', 'Australe', 'lettuce', ''],
  ['Autumn Fire Stonecrop', 'Sedum spectabile', 'hylotelephium', 'showy stonecrop, stonecrop, sedum spectabile'],
  ['Avocado', 'Avocado', 'avocado', ''],
  ['Beets', 'Beet', 'beet', 'beetroot'],
  ['Belstar Broccoli', 'Belstar', 'broccoli', ''],
  ['Big Boy', 'Big Boy', 'tomato', ''],
  ['Bitter Melon', 'Bitter Melon', 'bitter_melon', 'bitter gourd, karela'],
  ['Black Cherry', 'Black Cherry', 'tomato', ''],
  ['Black Olive', 'Black Olive', 'pepper', ''],
  ['Blackberry', 'Allegheny Blackberry', 'blackberry', ''],
  ['Blueberries', 'High Bush', 'blueberry', ''],
  ['Brentwood Leaf Lettuce', 'Brentwood', 'lettuce', ''],
  ['Broccoli', 'Broccoli', 'broccoli', ''],
  ['Bush Early Girl', 'Bush Early Girl', 'tomato', ''],
  ['Cabbage', 'Cabbage (unknown)', 'cabbage', ''],
  ['Cantaloupe', 'Cantaloupe', 'melon', 'cantaloupe, muskmelon, honeydew'],
  ['Capeliente', 'Capeliente', 'pepper', ''],
  ['Carmen', 'Carmen', 'pepper', ''],
  ['Cavendish Strawberry', 'Cavendish', 'strawberry', ''],
  ['Cayenne Blend', 'Cayenne Blend', 'pepper', ''],
  ['Celebrity', 'Celebrity', 'tomato', ''],
  ['Celebrity Rescue', 'Celebrity', 'tomato', ''],
  ['Charentais', 'Charentais', 'melon', 'cantaloupe, muskmelon, honeydew'],
  ['Cherokee Green', 'Cherokee Green', 'tomato', ''],
  ['Cherokee Green (Rescue)', 'Cherokee Green', 'tomato', ''],
  ['Cherry Falls', 'Cherry Falls', 'tomato', ''],
  ['Cherry Hot', 'Cherry Hot', 'pepper', ''],
  ['Cherry Rescue 1', 'Cherry', 'tomato', ''],
  ['Cherry Stuffer', 'Cherry Stuffer (Burpee)', 'pepper', ''],
  ['Chili Red', 'Chili Red', 'pepper', ''],
  ['Chilly Chill', 'Chilly Chill', 'pepper', ''],
  ['Chinese 5-Color', 'Chinese 5-Color', 'pepper', ''],
  ['Chives', 'Chives', 'chives', ''],
  ['Chocolate Mint', 'Chocolate Mint', 'mint', ''],
  ['Christmas Cactus', 'Christmas Cactus', 'christmas_cactus', 'schlumbergera'],
  ['Chrysanthemum', 'Chrysanthemum', 'chrysanthemum', ''],
  ['Cisneros', 'Cisneros', 'tomatillo', 'husk tomato'],
  ['Citronella', 'Citronella Geranium', 'geranium', 'pelargonium'],
  ['Clemson Spineless 80', 'Clemson Spineless 80', 'okra', 'lady\'s finger, bhindi'],
  ['Cobaea scandens (Violet)', 'Cobaea scandens (Violet)', 'cobaea', ''],
  ['Collards', 'Collards', 'collard', 'collard greens'],
  ['Combo Annuals', null, null, ''],
  ['Container Strawberry', 'Strawberry', 'strawberry', ''],
  ['Contender Bush Bean', 'Contender', 'bean', 'green bean, snap bean, string bean'],
  ['Copenhagen Market Cabbage', 'Copenhagen Market', 'cabbage', ''],
  ['Copper Stonecrop', 'Golden Sedum', 'sedum', 'stonecrop'],
  ['Cowhorn', 'Cowhorn', 'pepper', ''],
  ['Creme Sausage', 'Banana Creme', 'tomato', ''],
  ['Crimson Sweet', 'Crimson Sweet', 'watermelon', ''],
  ['Cubanelle', 'Cubanelle', 'pepper', ''],
  ['Cucamelon', 'Cucamelon', 'cucamelon', 'mouse melon, mexican sour gherkin'],
  ['Czech\'s Bush', 'Czech\'s Bush', 'tomato', ''],
  ['Danvers 126 Carrot', 'Danvers 126', 'carrot', ''],
  ['Dark Green Zucchini', 'Dark Green Zucchini', 'squash', 'zucchini, courgette'],
  ['Del Tonet', 'Del Tonet', 'tomato', ''],
  ['Delicious', 'Delicious', 'tomato', ''],
  ['Dester', 'Dester', 'tomato', ''],
  ['Dill', 'Dill \'Bouquet\'', 'dill', ''],
  ['Dragon Roll', 'Dragon Roll', 'pepper', ''],
  ['Dwarf Blue Curled Kale', 'Dwarf Blue Curled (Vates)', 'kale', ''],
  ['Easy Wave Berry Velour Petunia', 'Easy Wave Berry Velour', 'petunia', ''],
  ['Echeveria', 'Echeveria', 'echeveria', ''],
  ['Echeveria \'Perle von Nurnberg\'', 'Echeveria \'Perle von Nurnberg\'', 'echeveria', ''],
  ['Edible Beauties', 'Edible Beauties', 'flower_mix', ''],
  ['Eva Purple Ball', 'Eva Purple Ball', 'tomato', ''],
  ['Fairway Orange Coleus', 'Fairway Orange', 'coleus', 'plectranthus'],
  ['Fairway Orange Coleus Clone 1', 'Fairway Orange', 'coleus', 'plectranthus'],
  ['Fantasia Salmon Geranium', 'Fantasia Salmon', 'geranium', 'pelargonium'],
  ['Fingerling Potatoes', 'Fingerling', 'potato', ''],
  ['Flat of Italy Bulb Cipollini Onion', 'Flat of Italy', 'onion', ''],
  ['Floradade', 'Floradade', 'tomato', ''],
  ['Foxglove', 'Foxglove', 'foxglove', 'digitalis'],
  ['French Tarragon', 'French Tarragon', 'tarragon', ''],
  ['Garden Sage', 'Garden Sage', 'sage', 'salvia'],
  ['Garlic', 'Garlic (hardneck)', 'garlic', ''],
  ['Garlic Chives', 'Garlic Chives', 'chives', ''],
  ['Gatherer\'s Gold', 'Gatherer\'s Gold', 'pepper', ''],
  ['Geranium Cutting', 'Geranium', 'geranium', 'pelargonium'],
  ['Fuchsia Geranium', 'Geranium', 'geranium', 'pelargonium'],
  ['Ghost', 'Ghost', 'pepper', ''],
  ['Ginger', 'Ginger', 'ginger', ''],
  ['Gold Rush Bush Bean', 'Gold Rush', 'bean', 'green bean, snap bean, string bean'],
  ['Golden Sedum', 'Golden Sedum', 'sedum', 'stonecrop'],
  ['Goldenrod', 'Canada', 'goldenrod', ''],
  ['Gong Bao', 'Gong Bao (Kung Pao)', 'pepper', ''],
  ['Gourmet Blend Beets', 'Gourmet Blend', 'beet', 'beetroot'],
  ['Granadero', 'Granadero', 'tomato', ''],
  ['Graptosedum', 'Graptosedum', 'succulent', ''],
  ['Greek Oregano', 'Greek Oregano', 'oregano', ''],
  ['Green Fittonia', 'Green Fittonia', 'fittonia', 'nerve plant'],
  ['Green Flesh', 'Green Flesh', 'melon', 'cantaloupe, muskmelon, honeydew'],
  ['Green Magic', 'Green Magic', 'broccoli', ''],
  ['Gymnocalycium mihanovichii', 'Gymnocalycium mihanovichii', 'cactus', ''],
  ['Habanero', 'Habanero', 'pepper', ''],
  ['Haworthia / Gasteria (assorted)', 'Haworthia / Gasteria (assorted)', 'haworthia', ''],
  ['Holy Basil', 'Holy Basil (Tulsi)', 'basil', ''],
  ['Horseweed', 'Horseweed', 'horseweed', ''],
  ['Hosta', 'Hosta', 'hosta', ''],
  ['Hot & Spicy Oregano', 'Hot & Spicy Oregano', 'oregano', ''],
  ['Hoya Obovata', 'Hoya', 'hoya', ''],
  ['Hydrangeas', null, null, ''],
  ['Italian Parsley', 'Italian Parsley', 'parsley', ''],
  ['Jade Plant', 'Crassula ovata', 'jade', ''],
  ['Jalapeno', 'Jalapeno', 'pepper', ''],
  ['Japanese Maple', 'Japanese Maple', 'japanese_maple', 'acer'],
  ['Jaune du Poitou', 'Jaune du Poitou', 'leek', ''],
  ['Jet Star', 'Jet Star', 'tomato', ''],
  ['Jewel Mix Nasturtium', 'Jewel Mix Nasturtium', 'nasturtium', ''],
  ['King of the North', 'King of the North', 'pepper', ''],
  ['King Richard', 'King Richard', 'leek', ''],
  ['Kiwi Fern Coleus', 'Kiwi Fern', 'coleus', 'plectranthus'],
  ['Kori Sitakame', 'Kori Sitakame', 'pepper', ''],
  ['Kousa Dogwood', 'Kousa', 'dogwood', 'cornus'],
  ['Lacinato Dinosaur Kale', 'Lacinato (Dinosaur)', 'kale', ''],
  ['Lamb\'s Ear', 'Lamb\'s Ear', 'lamb_s_ear', ''],
  ['Lantana', 'Lantana', 'lantana', ''],
  ['Large Red Cherry', 'Large Red Cherry', 'tomato', ''],
  ['Lemon Thyme', 'Lemon Thyme', 'thyme', ''],
  ['Lemon Verbena', 'Lemon Verbena', 'lemon_verbena', 'aloysia'],
  ['Lemongrass', 'Lemongrass', 'lemongrass', ''],
  ['Lettuce Leaf Basil', 'Lettuce Leaf Basil', 'basil', ''],
  ['Little Gem Mini-Romaine Lettuce', 'Little Gem', 'lettuce', ''],
  ['Love\'s Fire', 'Love\'s Fire', 'succulent', ''],
  ['Mahogany Splendor Hybiscus', 'Mahogany Splendor', 'hibiscus', ''],
  ['Mammoth Dill', 'Mammoth', 'dill', ''],
  ['Manitoba', 'Manitoba', 'tomato', ''],
  ['Margaret Curtain', 'Margaret Curtain', 'tomato', ''],
  ['Marigolds', 'Marigolds', 'marigold', ''],
  ['Marvel of Four Seasons Butterhead Lettuce', 'Marvel of Four Seasons', 'lettuce', ''],
  ['Megatron Jalapeños', 'Megatron F1 (jumbo jalapeno)', 'pepper', ''],
  ['Mini Rose', 'Mini Rose', 'rose', ''],
  ['Minnesota Mini', 'Minnesota Mini', 'melon', 'cantaloupe, muskmelon, honeydew'],
  ['Moskvich Heirloom', 'Moskvich Heirloom', 'tomato', ''],
  ['Mountain Fresh Plus', 'Mountain Fresh Plus', 'tomato', ''],
  ['Neon Pothos', 'Neon', 'pothos', 'devil\'s ivy, epipremnum'],
  ['Neon Rose Calibrachoa', 'Neon Rose', 'calibrachoa', 'million bells'],
  ['New Mexico', 'New Mexico (Hatch-type)', 'pepper', ''],
  ['New Yorker', 'New Yorker', 'tomato', ''],
  ['Onion — scallion-type (thick blue-green, ID pending)', 'Onion (scallion-type)', 'bunching_onion', ''],
  ['Oregano', 'Oregano', 'oregano', ''],
  ['Oregon Spring', 'Oregon Spring', 'tomato', ''],
  ['Pachyphytum', 'Pachyphytum', 'succulent', ''],
  ['Palla Rossa Mavrik Radicchio', 'Palla Rossa Mavrik', 'radicchio', ''],
  ['Parris Island Cos Romaine Lettuce', 'Parris Island Cos', 'lettuce', ''],
  ['Peach tree', 'Peach', 'peach', ''],
  ['Penstemon', 'Penstemon', 'penstemon', 'beardtongue'],
  ['Peppermint', 'Peppermint', 'mint', ''],
  ['Petunia', 'Petunia', 'petunia', ''],
  ['Pick and Pop', 'Pick-N-Pop Yellow', 'pepper', ''],
  ['Pineapple Sage', 'Pineapple Sage', 'pineapple_sage', 'salvia, salvia elegans'],
  ['Pineapple Tomatillo', 'Pineapple Tomatillo', 'tomatillo', 'husk tomato'],
  ['Pineapple Tomato', 'Pineapple Tomato', 'tomato', ''],
  ['Ping Tung Long', 'Ping Tung Long', 'eggplant', 'aubergine'],
  ['Pink Fittonia', 'Pink Fittonia', 'fittonia', 'nerve plant'],
  ['Pinto Premium White Geranium', 'Pinto Premium White', 'geranium', 'pelargonium'],
  ['Piri Piri', 'Piri Piri', 'pepper', ''],
  ['Pothos', 'Golden Pothos', 'pothos', 'devil\'s ivy, epipremnum'],
  ['Pumpkin Jalapeno', 'Pumpkin Jalapeno', 'pepper', ''],
  ['Purple Basil', 'Purple Basil', 'basil', ''],
  ['Purple Blush Tomatillo', 'Purple blush', 'tomatillo', 'husk tomato'],
  ['Purple Heart', 'Purpurea', 'tradescantia', 'spiderwort, inch plant'],
  ['Purple Petra', 'Purple Petra Basil', 'basil', ''],
  ['Purple Vienna Kohlrabi', 'Purple Vienna', 'kohlrabi', 'german turnip'],
  ['Quadrato Rossi', 'Quadrato d\'Asti Rosso', 'pepper', ''],
  ['Rapini Broccoli Raab', 'Rapini', 'broccoli', ''],
  ['Red Acre Cabbage', 'Red Acre', 'cabbage', ''],
  ['Red Fittonia', 'Red Fittonia', 'fittonia', 'nerve plant'],
  ['Red Grape', 'Red Grape', 'tomato', ''],
  ['Red Mini Bell', 'Red Mini Bell', 'pepper', ''],
  ['Red Onions', 'Red Onion (long-day)', 'onion', ''],
  ['Red Raspberries', 'Red Raspberry', 'red_raspberry', ''],
  ['Red Rose (cultivar unknown)', 'Red Rose', 'rose', ''],
  ['Redbor Kale', 'Redbor', 'kale', ''],
  ['Ristra Cayenne II', 'Ristra Cayenne II', 'pepper', ''],
  ['Rosemary', 'Rosemary', 'rosemary', ''],
  ['Rosso Sicilian', 'Rosa Sicilian', 'tomato', ''],
  ['Royal Ruby Hens & Chicks', 'Royal Ruby', 'sempervivum', ''],
  ['Russet Potato', 'Russet', 'potato', ''],
  ['Russian Tarragon', 'Russian Tarragon', 'tarragon', ''],
  ['San Marzano rescue', 'San Marzano', 'tomato', ''],
  ['San Marzano Roma', 'San Marzano Roma', 'tomato', ''],
  ['Santa Fe Grande', 'Santa Fe Grande', 'pepper', ''],
  ['Scallion (thin clump)', 'Scallion', 'bunching_onion', ''],
  ['Scotch Bonnet', 'Scotch Bonnet', 'pepper', ''],
  ['Serranos', 'Serrano', 'pepper', ''],
  ['Shallots', 'Shallots', 'shallot', ''],
  ['Silver Helichrysum', 'Silver (Licorice Plant)', 'helichrysum', ''],
  ['Speckled Roman', 'Speckled Roman', 'tomato', ''],
  ['Speckled Roman Rescue', 'Speckled Roman', 'tomato', ''],
  ['Spider Plant', 'Spider Plant', 'spider_plant', 'chlorophytum'],
  ['Strawberries', 'Early June', 'strawberry', ''],
  ['Stupice', 'Stupice', 'tomato', ''],
  ['Sub Arctic Plenty', 'Sub Arctic Plenty', 'tomato', ''],
  ['Sugar Baby', 'Sugar Baby', 'watermelon', ''],
  ['Sugar Rush Peach', 'Sugar Rush Peach', 'pepper', ''],
  ['Summer Pastels Yarrow', 'Summer Pastels', 'yarrow', 'achillea'],
  ['Sun Sugar', 'Sun Sugar', 'tomato', ''],
  ['Sunny Susy White Halo Thunbergia', 'Sunny Susy White Halo', 'thunbergia', 'black-eyed susan vine'],
  ['Sunray', 'Sunray', 'tomato', ''],
  ['Super Sweet 100', 'Super Sweet 100', 'tomato', ''],
  ['Super Sweet 100 Rescue', 'Super Sweet 100', 'tomato', ''],
  ['Suyo Long', 'Suyo Long', 'cucumber', ''],
  ['Sweet Basil', 'Ocimum basilicum \'Sweet\'', 'basil', ''],
  ['Sweet Bay Laurel', 'Sweet Bay', 'bay', 'bay laurel'],
  ['Sweet Potato', 'Sweet Potato', 'sweet_potato', ''],
  ['Sweet Potatoes', 'Sweet Potato', 'sweet_potato', ''],
  ['Tatli Kil Sivri', 'Sweet Sivri', 'pepper', ''],
  ['Tavera Filet Bush Bean', 'Tavera', 'bean', 'green bean, snap bean, string bean'],
  ['Tender Sweet Orange', 'Tender Sweet Orange', 'watermelon', ''],
  ['Tendersweet Carrot', 'Tendersweet', 'carrot', ''],
  ['Thai Basil', 'Thai Basil', 'basil', ''],
  ['Thai Dragon', 'Thai Dragon', 'pepper', ''],
  ['Thessaloniki', 'Thessaloniki', 'tomato', ''],
  ['Tie-Dye Tomato', 'Tie-Dye', 'tomato', ''],
  ['Tradescantia', 'Tradescantia zebrina', 'tradescantia', 'spiderwort, inch plant'],
  ['Tradescantia Cuttings Experiment.', 'Tradescantia', 'tradescantia', 'spiderwort, inch plant'],
  ['Tres Fine', 'Tres Fine', 'endive', ''],
  ['Tuberous Begonia (bronze-leaf, hanging)', 'Tuberous Begonia', 'begonia', ''],
  ['Tulsi Basil', 'Holy Basil (Tulsi)', 'basil', ''],
  ['Tumeric', null, null, ''],
  ['Ukrainian Purple', 'Ukrainian Purple', 'tomato', ''],
  ['Unknown Bell', 'Bell Pepper (Unknown)', 'pepper', ''],
  ['Unknown Sweet Long', 'Unknown Sweet Long', 'pepper', ''],
  ['Unknown Sweet Orange', 'Sweet Orange Pepper (Unknown)', 'pepper', ''],
  ['Unknown Tomato Cuttings', 'Unknown', 'tomato', ''],
  ['Valencia', 'Valencia', 'tomato', ''],
  ['Wild Bergamot', 'Wild Bergamot', 'bee_balm', 'monarda, bergamot'],
  ['Wild Wineberry', 'Wild Wineberry', 'wineberry', ''],
  ['Wishbone Flower (Torenia)', 'Wishbone Flower', 'torenia', ''],
  ['Yatsufusa', 'Yatsufusa', 'pepper', ''],
  ['Yellow Brandywine', 'Yellow Brandywine', 'tomato', ''],
  ['Yellow Onions', 'Yellow Onion (long-day)', 'onion', ''],
  ['Yellow Pear', 'Yellow Pear', 'tomato', ''],
  ['Yukon Gold', 'Yukon Gold', 'potato', ''],
  ['Zephyr Squash', 'Zephyr', 'squash', 'zucchini, courgette'],
  ['Zonal Geranium', 'Zonal Geranium', 'geranium', 'pelargonium'],
]

const hex = (n) => n.toString(16).padStart(12, '0')
const varietyIds = new Map()
const varietyIdOf = (name) => {
  if (!varietyIds.has(name)) varietyIds.set(name, `00000000-0000-4000-9000-${hex(varietyIds.size + 1)}`)
  return varietyIds.get(name)
}

// The ?view=picker row shape VoiceHarvest reads (id, name, archived_at, variety_ref.{id,name,
// crop_type_slug,default_unit}), with `crop_aliases` attached only when non-empty, exactly as the page
// decorates a row. default_unit is null throughout, so the 'count' fallback is what an assumed quantity uses.
export const VOCAB = ROWS.map(([name, variety, crop, aliases], i) => {
  const variety_ref = variety == null
    ? null
    : { id: varietyIdOf(variety), name: variety, crop_type_slug: crop, default_unit: null }
  const row = { id: `00000000-0000-4000-8000-${hex(i + 1)}`, name, archived_at: null, variety_ref }
  const cropAliases = splitCropAliases(aliases)
  return cropAliases.length ? { ...row, crop_aliases: cropAliases } : row
})

export const byName = (name) => {
  const hits = VOCAB.filter((p) => p.name === name)
  if (hits.length !== 1) throw new Error(`fixture: ${hits.length} plantings named ${name}`)
  return hits[0]
}
