-- V5-VARIETYHYBRIDFLAG-001 — 0b-data.sql
-- GENERATED by gen-0b-data.mjs. Do not hand-edit: fix the payload or the mapping and re-run.
--
-- 79 rows written, 1 skipped.
-- breeding_system: {"open_pollinated":41,"unknown":18,"f1":19,"landrace":1}
-- breeding_source: {"reference_work":13,"inference":19,"breeder":3,"vendor_catalog":42,"grower_record":2}
--
-- Every UPDATE is guarded on deleted_at IS NULL. A soft-deleted variety is not repaired by
-- a backfill: it is out of the app's world, and writing to it would make the post-gate
-- counts disagree with what any user-facing surface can see.
--
-- NOT LOADED, deliberately: inventory_items.metadata heirloom / open_pollinated / hybrid_f1.
-- They partition by vendor and Mary's Heirloom Seeds is 36-for-36 'heirloom: true' including
-- a variety named 'Biquinho Yellow F1'. This payload is independent research with a named
-- source per row.
--
-- SKIPPED:
--   Yellow Pear — no variety_id — unmatched against the live roster

BEGIN;

-- Ghost — OP
--   src: Bosland & Baral, HortScience 42(2):222–224, 2007 PDF
UPDATE public.plant_varieties SET
    breeding_system = 'open_pollinated',
    breeding_source = 'reference_work',
    breeding_confidence = 'high',
    variety_rank = 'cultivar'
  WHERE id = '5bbc762a-7d19-4a6a-8ddc-f191329d9c68' AND deleted_at IS NULL;

-- Habanero — ID?
--   src: Wikipedia, Scotch bonnet (habanero & scotch bonnet = same species); NMSU CR706 (habanero pod type, 3 cultivars)
UPDATE public.plant_varieties SET
    breeding_system = 'unknown',
    breeding_source = 'inference',
    breeding_confidence = 'low',
    variety_rank = 'market_class'
  WHERE id = 'bfac627f-aa6a-4e58-9665-0a1b174bce68' AND deleted_at IS NULL;

-- Scotch Bonnet — ID? — most Scotch Bonnet seed sold is OP
--   src: Wikipedia, Scotch bonnet
UPDATE public.plant_varieties SET
    breeding_system = 'unknown',
    breeding_source = 'inference',
    breeding_confidence = 'low',
    variety_rank = 'market_class'
  WHERE id = '68472e88-515d-47a1-8edc-84fb2ec3e34b' AND deleted_at IS NULL;

-- Armageddon F1 — F1 (named)
--   src: Wikipedia, Armageddon (pepper)); Tozer variety sheet (PDF is image-only, text not machine-readable — link)
UPDATE public.plant_varieties SET
    breeding_system = 'f1',
    breeding_source = 'breeder',
    breeding_confidence = 'high',
    variety_rank = 'cultivar'
  WHERE id = '9a084c0d-9813-46cc-b30a-b2469befb12a' AND deleted_at IS NULL;

-- Sugar Rush Peach — OP
--   src: Specialty Produce; Baker Creek
UPDATE public.plant_varieties SET
    breeding_system = 'open_pollinated',
    breeding_source = 'reference_work',
    breeding_confidence = 'high',
    variety_rank = 'cultivar'
  WHERE id = 'becaec22-7572-4ed5-9765-9bb2e0e4ec03' AND deleted_at IS NULL;

-- Piri Piri — ID? (frutescens piri piri is OP)
--   src: Wikimedia Commons, C. frutescens 'Piri Piri'; Wikipedia, Piri piri; Wikipedia, Bird's eye chili; Truelove Seeds "Piri Piri Mix"; Cornell Botanic Garde
UPDATE public.plant_varieties SET
    breeding_system = 'unknown',
    breeding_source = 'inference',
    breeding_confidence = 'low',
    variety_rank = 'market_class'
  WHERE id = 'ff1adb23-63b8-46c2-b7de-05f32cc5b151' AND deleted_at IS NULL;

-- Cowhorn — OP
--   src: True Leaf Market ("Pepper Seeds – Hot – Cowhorn Hot", Heirloom badge)
UPDATE public.plant_varieties SET
    breeding_system = 'open_pollinated',
    breeding_source = 'vendor_catalog',
    breeding_confidence = 'high',
    variety_rank = 'cultivar'
  WHERE id = 'b29c6b0c-bf15-4655-bf53-ed3122a8ec6a' AND deleted_at IS NULL;

-- Black Olive — OP
--   src: All-America Selections; True Leaf Market ("open pollinated… Capsicum annuum")
UPDATE public.plant_varieties SET
    breeding_system = 'open_pollinated',
    breeding_source = 'reference_work',
    breeding_confidence = 'high',
    variety_rank = 'cultivar'
  WHERE id = 'dc0603ee-7064-4270-b817-780ffe5da290' AND deleted_at IS NULL;

-- Megatron F1 (jumbo jalapeño) (db: Megatron F1 (jumbo jalapeno)) — F1 (named)
--   src: Hoss; Harris Seeds; contradicting listing: Amazon
UPDATE public.plant_varieties SET
    breeding_system = 'f1',
    breeding_source = 'vendor_catalog',
    breeding_confidence = 'high',
    variety_rank = 'cultivar'
  WHERE id = '08131dd8-3282-48e9-8443-0eaa1026ffeb' AND deleted_at IS NULL;

-- Serrano — ID?
--   src: NMSU CR706
UPDATE public.plant_varieties SET
    breeding_system = 'unknown',
    breeding_source = 'inference',
    breeding_confidence = 'low',
    variety_rank = 'market_class'
  WHERE id = '35f01275-010c-485b-968c-c0fc4e510859' AND deleted_at IS NULL;

-- Ancho — ID?
--   src: NMSU CR706
UPDATE public.plant_varieties SET
    breeding_system = 'unknown',
    breeding_source = 'inference',
    breeding_confidence = 'low',
    variety_rank = 'market_class'
  WHERE id = '8247a874-9ddb-40cb-a2b4-7cee83109a72' AND deleted_at IS NULL;

-- Chinese 5-Color — OP
--   src: Specialty Produce; Baker Creek
UPDATE public.plant_varieties SET
    breeding_system = 'open_pollinated',
    breeding_source = 'reference_work',
    breeding_confidence = 'high',
    variety_rank = 'cultivar'
  WHERE id = '690c3f11-60a4-49b0-9ee9-9e08a2c57502' AND deleted_at IS NULL;

-- Capeliente — ID? — UNRESOLVED (lean hybrid)
--   src: Ball Seed PlantInfo; Ball bench card PDF; Ball 2026 catalog p.102
UPDATE public.plant_varieties SET
    breeding_system = 'unknown',
    breeding_source = 'inference',
    breeding_confidence = 'medium',
    variety_rank = 'market_class'
  WHERE id = '7e14c699-9ed1-4566-ac46-c7677cb91da3' AND deleted_at IS NULL;

-- Chili Red — ID? — UNRESOLVED
--   src: Searched without result: Brave, DuckDuckGo, Bing, Ecosia, Ball Seed catalogue. See §Coverage & limits.
UPDATE public.plant_varieties SET
    breeding_system = 'unknown',
    breeding_source = 'inference',
    breeding_confidence = 'medium',
    variety_rank = 'market_class'
  WHERE id = '37e333e2-a3c4-41f8-a732-c6f41a67f953' AND deleted_at IS NULL;

-- Yatsufusa — OP
--   src: True Leaf Market ("Pepper Seeds – Hot – Japanese Yatsufusa", Heirloom)
UPDATE public.plant_varieties SET
    breeding_system = 'open_pollinated',
    breeding_source = 'vendor_catalog',
    breeding_confidence = 'high',
    variety_rank = 'cultivar'
  WHERE id = '467084e4-e991-4c8a-8c2d-f9d55f1117d2' AND deleted_at IS NULL;

-- Anaheim — ID?
--   src: NMSU CR706
UPDATE public.plant_varieties SET
    breeding_system = 'unknown',
    breeding_source = 'inference',
    breeding_confidence = 'low',
    variety_rank = 'market_class'
  WHERE id = '64dcb174-1084-486e-9cd9-847deda89781' AND deleted_at IS NULL;

-- Bulgarian Carrot (Shipka) — OP
--   src: Fedco Seeds; Experimental Farm Network
UPDATE public.plant_varieties SET
    breeding_system = 'open_pollinated',
    breeding_source = 'vendor_catalog',
    breeding_confidence = 'high',
    variety_rank = 'cultivar'
  WHERE id = 'c03b71ce-963d-482c-ad1d-19ddcdb69b9b' AND deleted_at IS NULL;

-- Carmen — 🚩 F1 — name does not say so
--   src: Johnny's Selected Seeds; Johnny's breeding history
UPDATE public.plant_varieties SET
    breeding_system = 'f1',
    breeding_source = 'vendor_catalog',
    breeding_confidence = 'high',
    variety_rank = 'cultivar'
  WHERE id = '4f941e32-2e71-45f0-a71c-accf4c9cf100' AND deleted_at IS NULL;

-- Cayenne Blend — OP — but a deliberate MIXTURE
--   src: True Leaf Market
UPDATE public.plant_varieties SET
    breeding_system = 'unknown',
    breeding_source = 'vendor_catalog',
    breeding_confidence = 'high',
    variety_rank = 'blend'
  WHERE id = 'e3852f98-a83a-40f9-a078-85bde4f9596e' AND deleted_at IS NULL;

-- Cherry Hot — ID?
--   src: True Leaf Market; Johnny's Capperino F1
UPDATE public.plant_varieties SET
    breeding_system = 'unknown',
    breeding_source = 'inference',
    breeding_confidence = 'low',
    variety_rank = 'market_class'
  WHERE id = 'f7dd614d-ad1a-4fd6-98ea-a5b3d1022849' AND deleted_at IS NULL;

-- Cherry Stuffer (Burpee) — 🚩 F1 — name does not say so
--   src: Burpee
UPDATE public.plant_varieties SET
    breeding_system = 'f1',
    breeding_source = 'vendor_catalog',
    breeding_confidence = 'high',
    variety_rank = 'cultivar'
  WHERE id = '2dc44527-97a4-46f9-a419-cc813e411bb3' AND deleted_at IS NULL;

-- Cubanelle — ID? — traditional type is OP; low risk
--   src: Wikipedia, Cubanelle
UPDATE public.plant_varieties SET
    breeding_system = 'unknown',
    breeding_source = 'inference',
    breeding_confidence = 'low',
    variety_rank = 'market_class'
  WHERE id = '5a42b613-7375-4883-a17a-ababc3facd04' AND deleted_at IS NULL;

-- Dragon Roll — 🚩 F1 — name does not say so
--   src: Burpee
UPDATE public.plant_varieties SET
    breeding_system = 'f1',
    breeding_source = 'vendor_catalog',
    breeding_confidence = 'high',
    variety_rank = 'cultivar'
  WHERE id = '0500bd80-0944-4073-8308-e8175ef2f46c' AND deleted_at IS NULL;

-- Gatherer's Gold — OP
--   src: Territorial Seed; Nichols Garden Nursery; Experimental Farm Network
UPDATE public.plant_varieties SET
    breeding_system = 'open_pollinated',
    breeding_source = 'vendor_catalog',
    breeding_confidence = 'high',
    variety_rank = 'cultivar'
  WHERE id = 'd87228fc-9ce5-4123-8723-4ec974e383fc' AND deleted_at IS NULL;

-- Gong Bao (Kung Pao) — 🚩 F1 — name does not say so (with a source conflict)
--   src: Reimer Seeds; Specialty Produce; conflicting: All U Need Garden Supply
UPDATE public.plant_varieties SET
    breeding_system = 'f1',
    breeding_source = 'reference_work',
    breeding_confidence = 'high',
    variety_rank = 'cultivar'
  WHERE id = '8bf04a1d-4985-451f-8b01-d2e4707b45ea' AND deleted_at IS NULL;

-- Jalapeno — ID?
--   src: NMSU CR706
UPDATE public.plant_varieties SET
    breeding_system = 'unknown',
    breeding_source = 'inference',
    breeding_confidence = 'low',
    variety_rank = 'market_class'
  WHERE id = 'b8d4cf08-1498-4ec0-8448-93b35f4264bb' AND deleted_at IS NULL;

-- Kori Sitakame — OP — landrace
--   src: Native Seeds/SEARCH
UPDATE public.plant_varieties SET
    breeding_system = 'landrace',
    breeding_source = 'inference',
    breeding_confidence = 'high',
    variety_rank = 'cultivar'
  WHERE id = '6569aaf2-b6a9-4da5-81d8-a04702af5f9f' AND deleted_at IS NULL;

-- Pick-N-Pop Yellow — 🚩 F1 — name does not say so
--   src: All-America Selections; Jung Seed
UPDATE public.plant_varieties SET
    breeding_system = 'f1',
    breeding_source = 'reference_work',
    breeding_confidence = 'high',
    variety_rank = 'cultivar'
  WHERE id = '4c30aa40-9f5c-4b6a-b3f8-1f704568fa9a' AND deleted_at IS NULL;

-- Pumpkin Jalapeno — OP
--   src: Baker Creek; NMSU CR706
UPDATE public.plant_varieties SET
    breeding_system = 'open_pollinated',
    breeding_source = 'reference_work',
    breeding_confidence = 'high',
    variety_rank = 'cultivar'
  WHERE id = '325aed4a-1e21-487a-a66d-e4e38f72fafe' AND deleted_at IS NULL;

-- Quadrato d'Asti Rosso — OP
--   src: Aggregated vendor listings (True Leaf Market, Smart Gardener, Trade Winds Fruit, Kitchen Garden Seeds) via Brave results, fetched 2026-09-02
UPDATE public.plant_varieties SET
    breeding_system = 'open_pollinated',
    breeding_source = 'vendor_catalog',
    breeding_confidence = 'high',
    variety_rank = 'cultivar'
  WHERE id = '4bea570f-38d6-4c91-aabd-a8799c9697ff' AND deleted_at IS NULL;

-- Red Mini Bell — ID?
--   src: True Leaf Market
UPDATE public.plant_varieties SET
    breeding_system = 'unknown',
    breeding_source = 'inference',
    breeding_confidence = 'medium',
    variety_rank = 'market_class'
  WHERE id = '2d817dcd-2d8e-45cf-9317-e562915b69b3' AND deleted_at IS NULL;

-- Ristra Cayenne II — 🚩 Hybrid — high confidence, but the Ball page is silent
--   src: True Leaf Market, Ristra Cayenne F1; Ball Seed, Ristra Cayenne II
UPDATE public.plant_varieties SET
    breeding_system = 'f1',
    breeding_source = 'breeder',
    breeding_confidence = 'high',
    variety_rank = 'cultivar'
  WHERE id = 'bd11098f-d239-4a69-bb61-49a19a8e1488' AND deleted_at IS NULL;

-- Santa Fe Grande — OP
--   src: Everwilde Farms; Trade Winds Fruit
UPDATE public.plant_varieties SET
    breeding_system = 'open_pollinated',
    breeding_source = 'vendor_catalog',
    breeding_confidence = 'high',
    variety_rank = 'cultivar'
  WHERE id = 'd0c90b05-4902-4ef8-b1da-356f70877383' AND deleted_at IS NULL;

-- Sunbright — OP
--   src: Urban Farmer; Holmes Seed
UPDATE public.plant_varieties SET
    breeding_system = 'open_pollinated',
    breeding_source = 'vendor_catalog',
    breeding_confidence = 'high',
    variety_rank = 'cultivar'
  WHERE id = 'f0f2ed77-d3a5-418b-975c-fca44c11cd4c' AND deleted_at IS NULL;

-- Sweet Sivri — OP
--   src: Thresh Seed Co.
UPDATE public.plant_varieties SET
    breeding_system = 'open_pollinated',
    breeding_source = 'vendor_catalog',
    breeding_confidence = 'high',
    variety_rank = 'cultivar'
  WHERE id = 'f6ca07ba-1792-4fbd-bec9-c8e88316f8e1' AND deleted_at IS NULL;

-- Thai Dragon — 🚩 F1 — name does not say so
--   src: Urban Farmer; Sandia Seed
UPDATE public.plant_varieties SET
    breeding_system = 'f1',
    breeding_source = 'vendor_catalog',
    breeding_confidence = 'high',
    variety_rank = 'cultivar'
  WHERE id = '9671e7a2-f8de-4557-9402-8685dfbdfed4' AND deleted_at IS NULL;

-- Bell Pepper (Unknown) — ID? — HIGHEST RISK
--   src: Species framing: Wikipedia, Capsicum (five cultivated species)
UPDATE public.plant_varieties SET
    breeding_system = 'unknown',
    breeding_source = 'inference',
    breeding_confidence = 'low',
    variety_rank = 'market_class'
  WHERE id = 'cddbdc68-470a-4b22-88e4-63eb5334f11f' AND deleted_at IS NULL;

-- Chilly Chill — 🚩 F1
--   src: PanAmerican Seed GrowerFacts; All-America Selections
UPDATE public.plant_varieties SET
    breeding_system = 'f1',
    breeding_source = 'breeder',
    breeding_confidence = 'high',
    variety_rank = 'cultivar'
  WHERE id = '6ac055ac-4830-4556-ba62-2d68054fa9dc' AND deleted_at IS NULL;

-- 1884 — OP (heirloom)
--   src: Thresh Seed Co. (the source in the garden's own record); Reimer Seeds "Open Pollinated"; Renaissance Farms. WV, reportedly found after the 1884 Ohio R
UPDATE public.plant_varieties SET
    breeding_system = 'open_pollinated',
    breeding_source = 'vendor_catalog',
    breeding_confidence = 'high',
    variety_rank = 'cultivar'
  WHERE id = '7fe916d0-2445-4346-84db-1e1ec64d31d4' AND deleted_at IS NULL;

-- Banana Creme — OP — but see name note
--   src: Tradewinds Fruit — Banana Cream: "Open pollinated", "Determinate", "Also known as Cream Sausage", 80 d. Botanical Interests — Cream Sausage (the sourc
UPDATE public.plant_varieties SET
    breeding_system = 'open_pollinated',
    breeding_source = 'vendor_catalog',
    breeding_confidence = 'high',
    variety_rank = 'cultivar'
  WHERE id = 'c58ad0fa-265f-4dde-a6d8-98f7af77d9b2' AND deleted_at IS NULL;

-- Big Boy — F1
--   src: Burpee; Holmes Seed "Burpee's Big Boy F1"; Totally Tomatoes; and independently Univ. of Minnesota Extension names 'Big Boy' as a hybrid whose seed "ar
UPDATE public.plant_varieties SET
    breeding_system = 'f1',
    breeding_source = 'reference_work',
    breeding_confidence = 'high',
    variety_rank = 'cultivar'
  WHERE id = 'e609096d-16f6-42c3-94c0-aab89ab2e001' AND deleted_at IS NULL;

-- Black Cherry — OP (modern, 2003 — not an heirloom)
--   src: Johnny's Selected Seeds; Fedco; Adaptive Seeds; Harlequin's Gardens — bred by the late Vince Sapp
UPDATE public.plant_varieties SET
    breeding_system = 'open_pollinated',
    breeding_source = 'vendor_catalog',
    breeding_confidence = 'high',
    variety_rank = 'cultivar'
  WHERE id = '9a380ec8-46bb-4a8f-ad3b-ca8d53fcb80d' AND deleted_at IS NULL;

-- Bush Early Girl — F1
--   src: Harris Seeds "Tomato Bush Early Girl F1" (the source in the garden's own record); Victory Seeds "Bush Early Girl F1"; Burpee. UMN Extension names 'Ear
UPDATE public.plant_varieties SET
    breeding_system = 'f1',
    breeding_source = 'reference_work',
    breeding_confidence = 'high',
    variety_rank = 'cultivar'
  WHERE id = 'f151bdaa-69c8-4961-8346-17d2f7f9c757' AND deleted_at IS NULL;

-- Celebrity — F1
--   src: All-America Selections — "Tomato Celebrity hybrid", 1984 AAS winner (the source in the garden's own record); Johnny's; Totally Tomatoes
UPDATE public.plant_varieties SET
    breeding_system = 'f1',
    breeding_source = 'reference_work',
    breeding_confidence = 'high',
    variety_rank = 'cultivar'
  WHERE id = '832a8938-5612-42ad-9b4e-cea7a51befc3' AND deleted_at IS NULL;

-- Cherokee Green — OP (modern, 1997)
--   src: Johnny's: "A non-hybrid variety that can reproduce itself in kind"; "Craig LeHoullier sent us this seed as a selection out of heirloom Cherokee Purple
UPDATE public.plant_varieties SET
    breeding_system = 'open_pollinated',
    breeding_source = 'vendor_catalog',
    breeding_confidence = 'high',
    variety_rank = 'cultivar'
  WHERE id = 'ca2e43d6-4dee-4a59-95aa-72f4b37de187' AND deleted_at IS NULL;

-- Cherry (unspecified) (db: Cherry) — AMBIGUOUS — cannot classify
--   src: The garden's own record maps this name to a generic crop page (Univ. of Maryland Extension, growing tomatoes) — i.e. no cultivar was ever identified. 
UPDATE public.plant_varieties SET
    breeding_system = 'unknown',
    breeding_source = 'inference',
    breeding_confidence = 'low',
    variety_rank = 'market_class'
  WHERE id = 'f21e22d6-0556-4101-a470-0c8da3cb04ae' AND deleted_at IS NULL;

-- Cherry Falls — DISPUTED — hybrid vs OP
--   src: Botanical Interests states "Solanum lycopersicum (hybrid)" — and this is the source the garden's own record cites. John Scheepers Kitchen Garden Seeds
UPDATE public.plant_varieties SET
    breeding_system = 'unknown',
    breeding_source = 'vendor_catalog',
    breeding_confidence = 'low',
    variety_rank = NULL
  WHERE id = '826d26e4-fc42-422c-aa84-b8ba6130b743' AND deleted_at IS NULL;

-- Czech's Bush — OP (heirloom)
--   src: True Leaf Market "Open Pollinated"; Tim's Tomatoes "Open-Pollinated … Heirloom" (the source in the garden's own record); Wildrose Heritage.html). To t
UPDATE public.plant_varieties SET
    breeding_system = 'open_pollinated',
    breeding_source = 'vendor_catalog',
    breeding_confidence = 'high',
    variety_rank = 'cultivar'
  WHERE id = 'b2be3698-b782-4a6b-8879-435effc9fcce' AND deleted_at IS NULL;

-- Del Tonet — OP — by strong inference, NOT by label
--   src: Uprising Seeds: "From Catalonia, one of the centers of biodiversity for 'hanging tomatoes' ('de colgar' locally)", indeterminate, 70 d, stores "3+ mon
UPDATE public.plant_varieties SET
    breeding_system = 'open_pollinated',
    breeding_source = 'inference',
    breeding_confidence = 'medium',
    variety_rank = 'cultivar'
  WHERE id = '6b8e275b-c414-470d-baba-4b5dd12f0a3e' AND deleted_at IS NULL;

-- Delicious — OP
--   src: HRSeeds: "Open pollinated", indeterminate, 80 d, "Introduced by Burpee", "holds the world's record for largest tomato for 30+ years at 7 lbs 12 oz". T
UPDATE public.plant_varieties SET
    breeding_system = 'open_pollinated',
    breeding_source = 'vendor_catalog',
    breeding_confidence = 'high',
    variety_rank = 'cultivar'
  WHERE id = '37e1bc31-e383-4ca8-a251-88840c3dbc1d' AND deleted_at IS NULL;

-- Dester — OP (heirloom)
--   src: Seed Savers Exchange — SSE introduced it commercially in 2012; Thresh Seed Co. (the source in the garden's own record); Baker Creek. German → Dr. Herb
UPDATE public.plant_varieties SET
    breeding_system = 'open_pollinated',
    breeding_source = 'vendor_catalog',
    breeding_confidence = 'high',
    variety_rank = 'cultivar'
  WHERE id = '060d0712-e38c-4880-b796-6e218bc9b420' AND deleted_at IS NULL;

-- Eva Purple Ball — OP (heirloom)
--   src: Tomatofest "Open pollinated. Indeterminate."; Experimental Farm Network; Everwilde. Black Forest, Germany, late 1800s. Garden record cites Cornell CCE
UPDATE public.plant_varieties SET
    breeding_system = 'open_pollinated',
    breeding_source = 'vendor_catalog',
    breeding_confidence = 'high',
    variety_rank = 'cultivar'
  WHERE id = '446d59db-021b-4b03-874c-9d0a03cd16c8' AND deleted_at IS NULL;

-- Floradade — OP
--   src: True Leaf Market (the source in the garden's own record); Victory Seeds; Terroir/Underwood Gardens. Univ. of Florida, Homestead, released 1976
UPDATE public.plant_varieties SET
    breeding_system = 'open_pollinated',
    breeding_source = 'reference_work',
    breeding_confidence = 'high',
    variety_rank = 'cultivar'
  WHERE id = '7b355b73-391c-4cdd-b040-f1cd87a447d5' AND deleted_at IS NULL;

-- Granadero — F1
--   src: Johnny's Selected Seeds "Granadero — Organic (F1)" (the source in the garden's own record); High Mowing "Granadero F1"; Harris Seeds
UPDATE public.plant_varieties SET
    breeding_system = 'f1',
    breeding_source = 'vendor_catalog',
    breeding_confidence = 'high',
    variety_rank = 'cultivar'
  WHERE id = '2f91a147-706a-4b30-8d3c-9843c750aa15' AND deleted_at IS NULL;

-- Jet Star — F1
--   src: Fedco states "F-1 hybrid", compact indeterminate, 72 d (the source in the garden's own record); Harris Seeds "Tomato Jet Star F1" — Harris's own long-
UPDATE public.plant_varieties SET
    breeding_system = 'f1',
    breeding_source = 'vendor_catalog',
    breeding_confidence = 'high',
    variety_rank = 'cultivar'
  WHERE id = 'c1813eb3-2e60-4b31-9e85-e1354ba2a74e' AND deleted_at IS NULL;

-- Large Red Cherry — OP (heirloom)
--   src: True Leaf Market "open-pollinated, heirloom, and indeterminate" (the source in the garden's own record); Everwilde, listed as "Large Red Cherry Open P
UPDATE public.plant_varieties SET
    breeding_system = 'open_pollinated',
    breeding_source = 'vendor_catalog',
    breeding_confidence = 'high',
    variety_rank = 'cultivar'
  WHERE id = '7517d6b9-c733-431a-952e-7283adb90927' AND deleted_at IS NULL;

-- Manitoba — OP (heirloom)
--   src: West Coast Seeds (the source in the garden's own record); Bright Bush Farm, "Heirloom Determinate … Open Pollinated"; Totally Tomatoes; Heritage Harve
UPDATE public.plant_varieties SET
    breeding_system = 'open_pollinated',
    breeding_source = 'vendor_catalog',
    breeding_confidence = 'high',
    variety_rank = 'cultivar'
  WHERE id = 'ed695d19-042a-4627-8e23-e5e743c39f7e' AND deleted_at IS NULL;

-- Margaret Curtain — OP
--   src: Secret Seed Cartel — explicitly "Regular Leaf", "Indeterminate", organically grown, mid-season. Kōanga Institute (NZ) — "Indeterminate", large beefste
UPDATE public.plant_varieties SET
    breeding_system = 'open_pollinated',
    breeding_source = 'inference',
    breeding_confidence = 'high',
    variety_rank = 'cultivar'
  WHERE id = 'c7b43128-4d2c-4259-83d6-b615fff14d87' AND deleted_at IS NULL;

-- Moskvich Heirloom — OP (heirloom)
--   src: Johnny's Selected Seeds: "open pollinated, indeterminate", 60 d. TomatoFest, spelled Moskovich (the source in the garden's own record). Vavilov Instit
UPDATE public.plant_varieties SET
    breeding_system = 'open_pollinated',
    breeding_source = 'vendor_catalog',
    breeding_confidence = 'high',
    variety_rank = 'cultivar'
  WHERE id = 'de98ac1e-d4f1-417e-8e59-e6202dfaa742' AND deleted_at IS NULL;

-- Mountain Fresh Plus — F1
--   src: Johnny's "Mountain Fresh Plus — (F1)" (the source in the garden's own record); Holmes Seed "Mt. Fresh Plus F1"; Park Seed. Bred by Dr. Randy Gardner, 
UPDATE public.plant_varieties SET
    breeding_system = 'f1',
    breeding_source = 'vendor_catalog',
    breeding_confidence = 'high',
    variety_rank = 'cultivar'
  WHERE id = '9da384ee-d318-48ec-be25-09733ceaa594' AND deleted_at IS NULL;

-- New Yorker — OP
--   src: Sandia Seed (the source in the garden's own record); Totally Tomatoes, listed in its Open Pollinated category; Tradewinds Fruit. NY State Agricultural
UPDATE public.plant_varieties SET
    breeding_system = 'open_pollinated',
    breeding_source = 'vendor_catalog',
    breeding_confidence = 'high',
    variety_rank = 'cultivar'
  WHERE id = '3e1b9dbb-9dea-4eaa-a703-9c5d3a0cf02b' AND deleted_at IS NULL;

-- Oregon Spring — OP — with a real seed-saving catch
--   src: Territorial Seed (the source in the garden's own record); Victory Seeds; Fedco. Dr. James Baggett, Oregon State, released 1984. CATCH: it is parthenoc
UPDATE public.plant_varieties SET
    breeding_system = 'open_pollinated',
    breeding_source = 'vendor_catalog',
    breeding_confidence = 'high',
    variety_rank = 'cultivar'
  WHERE id = '8bcbd494-0694-413a-94a2-58adea9ac3c7' AND deleted_at IS NULL;

-- Pineapple Tomato — OP (heirloom) — leaf type disputed, name ambiguous
--   src: OP status well supported: TomatoFest, Specialty Produce, Everwilde. LEAF CONFLICT: Alliance of Native Seedkeepers (the source in the garden's own reco
UPDATE public.plant_varieties SET
    breeding_system = 'unknown',
    breeding_source = 'reference_work',
    breeding_confidence = 'low',
    variety_rank = 'market_class'
  WHERE id = 'bc71c506-f478-40b5-acfd-7ee1129e725c' AND deleted_at IS NULL;

-- Red Grape — F1 (most likely) — verify the packet
--   src: The garden's own record pins this to Harris Seeds "Tomato Red Grape F1" — verified live: F1 in the product name, "large, indeterminate plants", 70 d, 
UPDATE public.plant_varieties SET
    breeding_system = 'f1',
    breeding_source = 'inference',
    breeding_confidence = 'medium',
    variety_rank = 'cultivar'
  WHERE id = 'cd5dfccd-acfe-4e0f-b989-0f2de3050c9a' AND deleted_at IS NULL;

-- Rosa Sicilian — OP (heirloom)
--   src: Bucktown Seed Company "Rosa Sicilian" (the source in the garden's own record); True Leaf Market states "Rosso Sicilian can also be called Rosa Sicilia
UPDATE public.plant_varieties SET
    breeding_system = 'open_pollinated',
    breeding_source = 'vendor_catalog',
    breeding_confidence = 'high',
    variety_rank = 'cultivar'
  WHERE id = 'c466f3bc-30b6-4295-9b99-7516b98ecddb' AND deleted_at IS NULL;

-- San Marzano — OP (heirloom)
--   src: Johnny's "San Marzano II": "Open Pollinated … can reproduce itself in kind", indeterminate, 78 d, strain "selected by tomato breeder Emily Rose Haga f
UPDATE public.plant_varieties SET
    breeding_system = 'open_pollinated',
    breeding_source = 'vendor_catalog',
    breeding_confidence = 'high',
    variety_rank = 'cultivar'
  WHERE id = '46f5e31a-d014-40d9-8348-d8b08b32b2b5' AND deleted_at IS NULL;

-- San Marzano Roma — OP — but a different line from row 28; see warning
--   src: Sold as a determinate seed line by some vendors: Alliance of Native Seedkeepers, "San Marzano Roma (Determinate Seed Line)"; Sandia Seed sells "San Ma
UPDATE public.plant_varieties SET
    breeding_system = 'open_pollinated',
    breeding_source = 'vendor_catalog',
    breeding_confidence = 'high',
    variety_rank = 'cultivar'
  WHERE id = '7c68050c-0d21-4e79-9510-3248ff8cd72e' AND deleted_at IS NULL;

-- Speckled Roman — OP (modern, ~2000s — not an heirloom)
--   src: Johnny's (the source in the garden's own record); Tomato Growers Supply; Fedco; Victory Seeds. Bred by SSE member John Swenson from Antique Roman × Ba
UPDATE public.plant_varieties SET
    breeding_system = 'open_pollinated',
    breeding_source = 'vendor_catalog',
    breeding_confidence = 'high',
    variety_rank = 'cultivar'
  WHERE id = '1d9ee458-609c-4e42-8575-133e00d3f5aa' AND deleted_at IS NULL;

-- Stupice — OP (heirloom)
--   src: Territorial Seed: "Open Pollinated Variety", "Indeterminate potato-leaf variety", 60–65 d. Uprising Seeds; Terroir Seeds. Agricultural station at Stup
UPDATE public.plant_varieties SET
    breeding_system = 'open_pollinated',
    breeding_source = 'vendor_catalog',
    breeding_confidence = 'high',
    variety_rank = 'cultivar'
  WHERE id = '6510fa7d-aa43-478f-aee1-2d63092a58a9' AND deleted_at IS NULL;

-- Sub Arctic Plenty — OP
--   src: Totally Tomatoes, listed under "Medium-Small Open Pollinated Tomato Seeds"; Everwilde; Reimer Seeds; MIgardener (the source in the garden's own record
UPDATE public.plant_varieties SET
    breeding_system = 'open_pollinated',
    breeding_source = 'vendor_catalog',
    breeding_confidence = 'high',
    variety_rank = 'cultivar'
  WHERE id = '7c7f4597-5c4c-4388-ba8f-18babb593149' AND deleted_at IS NULL;

-- Sun Sugar — F1
--   src: Urban Farmer "SunSugar (F1)" (the source in the garden's own record); Holmes Seed "Sunsugar F1"; Tomato Growers Supply "Sun Sugar FT Hybrid"; Totally 
UPDATE public.plant_varieties SET
    breeding_system = 'f1',
    breeding_source = 'vendor_catalog',
    breeding_confidence = 'high',
    variety_rank = 'cultivar'
  WHERE id = 'a6825fd5-30dc-40d0-95fb-17e9f8fb91a5' AND deleted_at IS NULL;

-- Sunray — OP (heirloom)
--   src: Everwilde, listed as "Open Pollinated Tomato Seeds – 'Sunray'"; True Leaf Market "open-pollinated, heirloom … indeterminate"; Totally Tomatoes lists i
UPDATE public.plant_varieties SET
    breeding_system = 'open_pollinated',
    breeding_source = 'vendor_catalog',
    breeding_confidence = 'high',
    variety_rank = 'cultivar'
  WHERE id = '548c1568-9eb8-4e74-9b03-c9086043b426' AND deleted_at IS NULL;

-- Super Sweet 100 — F1
--   src: Burpee; Johnny's "Supersweet 100 F1"; HOSS; Wikipedia article on the cultivar. Note: the garden's own record has no cultivar-specific source for this 
UPDATE public.plant_varieties SET
    breeding_system = 'f1',
    breeding_source = 'reference_work',
    breeding_confidence = 'high',
    variety_rank = 'cultivar'
  WHERE id = 'ae27cbcb-de97-41ed-b8e0-996417314638' AND deleted_at IS NULL;

-- Thessaloniki — OP (heirloom)
--   src: Siskiyou Seeds (the source in the garden's own record): "A Greek heirloom tomato … introduced to the USA in the 1950's by Glecklers Seedsmen of Ohio",
UPDATE public.plant_varieties SET
    breeding_system = 'open_pollinated',
    breeding_source = 'grower_record',
    breeding_confidence = 'high',
    variety_rank = 'cultivar'
  WHERE id = '31a3db63-91d4-4255-99b8-d3d92519dc39' AND deleted_at IS NULL;

-- Tie-Dye — OP — but the name covers ≥3 varieties
--   src: The garden's own record resolves it to Fedco's Pink Berkeley Tie-Dye, verified live: "open pollinated", "Compact Indeterminate", 68 d, ~9 oz, "the col
UPDATE public.plant_varieties SET
    breeding_system = 'open_pollinated',
    breeding_source = 'vendor_catalog',
    breeding_confidence = 'high',
    variety_rank = 'cultivar'
  WHERE id = '4ef6cb98-1d80-463d-9426-f57d107d8b80' AND deleted_at IS NULL;

-- Ukrainian Purple — OP (heirloom)
--   src: Tim's Tomatoes: "Open-Pollinated Tomato" + "Heirloom Tomato", "Indeterminate", 75–80 d. MIgardener (the source in the garden's own record): heirloom, 
UPDATE public.plant_varieties SET
    breeding_system = 'open_pollinated',
    breeding_source = 'grower_record',
    breeding_confidence = 'high',
    variety_rank = 'cultivar'
  WHERE id = '6fc54973-c263-4d11-aaed-574ccf221af5' AND deleted_at IS NULL;

-- Unknown — Not a cultivar — cannot classify
--   src: No source exists for a variety named "Unknown". This is a placeholder in the garden database
UPDATE public.plant_varieties SET
    breeding_system = 'unknown',
    breeding_source = 'inference',
    breeding_confidence = 'low',
    variety_rank = 'market_class'
  WHERE id = 'b5ec43ed-dbd0-4282-9adb-52f8666925ef' AND deleted_at IS NULL;

-- Valencia — OP (heirloom)
--   src: Johnny's Selected Seeds (the source in the garden's own record): "Open-pollinated … can reproduce itself in kind", indeterminate, 76 d, "Our own selec
UPDATE public.plant_varieties SET
    breeding_system = 'open_pollinated',
    breeding_source = 'vendor_catalog',
    breeding_confidence = 'high',
    variety_rank = 'cultivar'
  WHERE id = '0ab2cf55-9977-4908-a2d3-d70a08f28fca' AND deleted_at IS NULL;

-- Yellow Brandywine — OP (heirloom) — two strains sold under this name
--   src: True Leaf Market (the source in the garden's own record): "open-pollinated, heirloom", "potato leaf … leaves are smooth rather than the regular serrat
UPDATE public.plant_varieties SET
    breeding_system = 'open_pollinated',
    breeding_source = 'vendor_catalog',
    breeding_confidence = 'high',
    variety_rank = 'cultivar'
  WHERE id = '6541c3fe-234f-477e-a603-a337cf0fac39' AND deleted_at IS NULL;

INSERT INTO public.schema_version (version, description, applied_at)
VALUES ('4.101.0-varietyhybridflag-001-data',
        'VARIETYHYBRIDFLAG backfill: 79 live cultivars given a researched breeding call with a named source per row. {"open_pollinated":41,"unknown":18,"f1":19,"landrace":1}. Generated by gen-0b-data.mjs from breeding-status-backfill.json; no vendor metadata loaded.',
        now())
ON CONFLICT (version) DO UPDATE SET applied_at = now(), description = EXCLUDED.description;

COMMIT;
