-- 0b-backfill.sql — GENERATED by backfill.gen.py. DO NOT EDIT BY HAND.
-- V5-SOURCEBACKFILL-001. Regenerate with:
--   python3 backfill.gen.py ../v5-sourceentity-001/proposed-sources.csv \
--     ../v5-sourceentity-001/dedupe-mapping.csv 0b-backfill.sql
--
-- Populates public.source from the REVIEWED catalogue and points plants / inventory_items at
-- it. Dave approved the run on 2026-09-04 with five medium-confidence KIND labels stated to
-- him explicitly (Bostrom Farms, Nettlepoint Farm, Liz Young, Panorama Tours, and
-- Gardener's Supply Company); every MERGE decision was already his.
--
-- THE FREE TEXT IS NOT TOUCHED. plants.source_ref and inventory_items.source are read as the
-- join key and never written, so this migration is reversible by nulling four columns —
-- which is exactly what 0r-rollback.sql does. That is why five medium-confidence category
-- labels were an acceptable price for shipping now: nothing is destroyed, and each is one
-- tap to correct from the picker.
--
-- IDEMPOTENT. Catalogue inserts are ON CONFLICT DO NOTHING; every UPDATE is guarded by
-- `IS NULL` on the column it sets, so a re-run cannot overwrite a value a human has since
-- corrected through the app. Re-running after a manual fix is safe and is a no-op for it.
--
-- SOFT-DELETED PARENTS ARE INCLUDED DELIBERATELY (no deleted_at filter on plants). 16 of the
-- 182 plants rows are soft-deleted; their provenance is history worth keeping, and the
-- Deleted-Planting History Rule says a withdrawn record does not retract what happened.

BEGIN;

-- ── 1. THE CATALOGUE ─────────────────────────────────────────────────────────────────────
-- 53 reviewed rows + the Unknown row = 54.
INSERT INTO public.source (name, kind, locality, address, website_url, notes, created_by)
VALUES
  ('Amazon', 'retail', NULL, NULL, 'https://www.amazon.com', NULL, 'system'),
  ('Belchertown Plant Swap', 'plant_swap', 'Belchertown, MA', NULL, NULL, NULL, 'system'),
  ('Bentley Seeds', 'seed_company', NULL, NULL, NULL, NULL, 'system'),
  ('Best Buy', 'retail', NULL, NULL, NULL, NULL, 'system'),
  ('Big Y', 'retail', NULL, NULL, NULL, NULL, 'system'),
  ('Bonnie Plants', 'brand', NULL, NULL, NULL, NULL, 'system'),
  ('Bostrom Farms', 'farm_stand', NULL, NULL, NULL, NULL, 'system'),
  ('Botanical Interests', 'seed_company', NULL, NULL, NULL, NULL, 'system'),
  ('Burpee', 'seed_company', NULL, NULL, NULL, NULL, 'system'),
  ('Chapley Gardens', 'nursery', 'Deerfield, MA', '397 Greenfield Rd', NULL, NULL, 'system'),
  ('Class Grass Garden Center', 'nursery', 'Granby, MA', NULL, NULL, NULL, 'system'),
  ('Emma Daley', 'person', NULL, NULL, NULL, NULL, 'system'),
  ('Four Phantoms Brewing Company', 'organization', 'Greenfield, MA', NULL, NULL, 'Brewery at 301 Wells St. Not a plant source in its own right - it is where Dave met Jen, a co-owner, who gave him 12 plants. The venue half of a person-met-at-a-place split.', 'system'),
  ('Gardener’s Supply Company', 'garden_center', 'Hadley, MA', NULL, NULL, 'Retail store. Stocks Botanical Interests, Seed Savers Exchange and High Mowing packets - 12 seed lots so far are branded goods bought here rather than mail-ordered.', 'system'),
  ('GoveeLife', 'brand', NULL, NULL, NULL, NULL, 'system'),
  ('Greenfield Farmers Co-op', 'market', 'Greenfield, MA', NULL, NULL, NULL, 'system'),
  ('Greenfield Farmers Market', 'market', 'Greenfield, MA', NULL, NULL, NULL, 'system'),
  ('Gurney''s Seed & Nursery Co.', 'seed_company', NULL, NULL, NULL, NULL, 'system'),
  ('Hadley Plant Swap', 'plant_swap', 'Hadley, MA', NULL, NULL, NULL, 'system'),
  ('Hart Farm', 'farm_stand', NULL, NULL, NULL, NULL, 'system'),
  ('Hatfield Plant Swap', 'plant_swap', 'Hatfield, MA', NULL, NULL, NULL, 'system'),
  ('High Mowing Organic Seeds', 'seed_company', NULL, NULL, NULL, NULL, 'system'),
  ('Hillfolk Seed Collective', 'seed_company', NULL, NULL, NULL, NULL, 'system'),
  ('Home Depot', 'retail', NULL, NULL, NULL, NULL, 'system'),
  ('Imogen', 'person', NULL, NULL, NULL, NULL, 'system'),
  ('Jen', 'person', 'Greenfield, MA', NULL, NULL, NULL, 'system'),
  ('Jen''s uncle', 'person', NULL, NULL, NULL, NULL, 'system'),
  ('Johnny''s Selected Seeds', 'seed_company', 'Winslow, ME', NULL, 'https://www.johnnyseeds.com', NULL, 'system'),
  ('Lake Valley Seed', 'seed_company', NULL, NULL, NULL, NULL, 'system'),
  ('Livingston Seed', 'seed_company', NULL, NULL, NULL, NULL, 'system'),
  ('Liz Young', 'person', NULL, NULL, NULL, NULL, 'system'),
  ('Long River Produce Market', 'market', 'Deerfield, MA', NULL, NULL, NULL, 'system'),
  ('Magic Wings', 'organization', 'South Deerfield, MA', NULL, 'https://magicwings.com/', NULL, 'system'),
  ('Mary''s Heirloom Seeds', 'seed_company', NULL, NULL, NULL, NULL, 'system'),
  ('Massachusetts Flower Growers Association', 'organization', NULL, NULL, NULL, NULL, 'system'),
  ('NaturesGoodGuys', 'brand', NULL, NULL, NULL, NULL, 'system'),
  ('Nettlepoint Farm', 'farm_stand', NULL, NULL, NULL, NULL, 'system'),
  ('Ojos de Luna', 'person', NULL, NULL, NULL, NULL, 'system'),
  ('Own garden', 'own_garden', NULL, NULL, NULL, NULL, 'system'),
  ('Panorama Tours', 'other', 'Austria', NULL, NULL, NULL, 'system'),
  ('Renee''s Garden', 'seed_company', NULL, NULL, NULL, NULL, 'system'),
  ('Sandia Seed Company', 'seed_company', NULL, NULL, NULL, NULL, 'system'),
  ('Seed Savers Exchange', 'seed_company', 'Decorah, IA', NULL, NULL, NULL, 'system'),
  ('Skawski Farms', 'nursery', NULL, NULL, 'https://www.skawskifarms.com', NULL, 'system'),
  ('Starview Gardens', 'nursery', NULL, NULL, NULL, NULL, 'system'),
  ('Sunderland trust stand', 'farm_stand', 'Sunderland, MA', NULL, NULL, NULL, 'system'),
  ('The Warren Place Flower Farm', 'nursery', NULL, NULL, NULL, NULL, 'system'),
  ('Toudura', 'brand', NULL, NULL, NULL, NULL, 'system'),
  ('Trust stand, Hadley', 'farm_stand', 'Hadley, MA', NULL, NULL, NULL, 'system'),
  ('Trust stand, Upper Road', 'farm_stand', 'Greenfield, MA', 'Upper Road', NULL, NULL, 'system'),
  ('UMass Amherst Libraries Common Seed Project', 'organization', 'Amherst, MA', NULL, 'https://guides.library.umass.edu/commonseed', NULL, 'system'),
  ('Walmart', 'retail', NULL, NULL, NULL, NULL, 'system'),
  ('Whately Plant Swap', 'plant_swap', 'Whately, MA', NULL, NULL, NULL, 'system'),
  ('Unknown', NULL, NULL, NULL, NULL, 'V5-SOURCEUNKNOWN-001. Use this when you were asked and genuinely do not know. It means something a blank cannot: a blank is indistinguishable from never having been asked, and cannot be counted or listed. Nothing was backfilled onto this row - every row pointing here was pointed here deliberately.', 'system')
ON CONFLICT DO NOTHING;

-- ── 2. THE POINTERS ──────────────────────────────────────────────────────────────────────
-- One statement per verbatim spelling, matched EXACTLY and scoped to its own parent column.
-- Exact match, not ILIKE or trim: the spellings ARE the data, and a fuzzy join here would
-- re-create by accident the conflation this whole entity exists to undo.

-- inventory_items.source: 'Amazon' (164 rows, new, high)
UPDATE public.inventory_items t SET
       source_id = (SELECT s.id FROM public.source s
                     WHERE s.name = 'Amazon' AND s.deleted_at IS NULL)
 WHERE t.source = 'Amazon'
   AND t.source_id IS NULL;

-- inventory_items.source: 'Amazon (GoveeLife)' (2 rows, split, high)
--   originator 'GoveeLife' via shop 'Amazon'
UPDATE public.inventory_items t SET
       source_id = (SELECT s.id FROM public.source s
                     WHERE s.name = 'GoveeLife' AND s.deleted_at IS NULL)
     , acquired_from_source_id = (SELECT s.id FROM public.source s
                                   WHERE s.name = 'Amazon' AND s.deleted_at IS NULL)
 WHERE t.source = 'Amazon (GoveeLife)'
   AND t.source_id IS NULL;

-- inventory_items.source: 'Amazon (NaturesGoodGuys)' (1 rows, split, high)
--   originator 'NaturesGoodGuys' via shop 'Amazon'
UPDATE public.inventory_items t SET
       source_id = (SELECT s.id FROM public.source s
                     WHERE s.name = 'NaturesGoodGuys' AND s.deleted_at IS NULL)
     , acquired_from_source_id = (SELECT s.id FROM public.source s
                                   WHERE s.name = 'Amazon' AND s.deleted_at IS NULL)
 WHERE t.source = 'Amazon (NaturesGoodGuys)'
   AND t.source_id IS NULL;

-- inventory_items.source: 'Amazon (Toudura)' (1 rows, split, high)
--   originator 'Toudura' via shop 'Amazon'
UPDATE public.inventory_items t SET
       source_id = (SELECT s.id FROM public.source s
                     WHERE s.name = 'Toudura' AND s.deleted_at IS NULL)
     , acquired_from_source_id = (SELECT s.id FROM public.source s
                                   WHERE s.name = 'Amazon' AND s.deleted_at IS NULL)
 WHERE t.source = 'Amazon (Toudura)'
   AND t.source_id IS NULL;

-- inventory_items.source: 'Belchertown Plant Swap' (2 rows, merge, high)
UPDATE public.inventory_items t SET
       source_id = (SELECT s.id FROM public.source s
                     WHERE s.name = 'Belchertown Plant Swap' AND s.deleted_at IS NULL)
 WHERE t.source = 'Belchertown Plant Swap'
   AND t.source_id IS NULL;

-- inventory_items.source: 'Bentley Seeds order #50330' (53 rows, new, high)
UPDATE public.inventory_items t SET
       source_id = (SELECT s.id FROM public.source s
                     WHERE s.name = 'Bentley Seeds' AND s.deleted_at IS NULL)
 WHERE t.source = 'Bentley Seeds order #50330'
   AND t.source_id IS NULL;

-- inventory_items.source: 'Best Buy' (1 rows, new, high)
UPDATE public.inventory_items t SET
       source_id = (SELECT s.id FROM public.source s
                     WHERE s.name = 'Best Buy' AND s.deleted_at IS NULL)
 WHERE t.source = 'Best Buy'
   AND t.source_id IS NULL;

-- inventory_items.source: 'Botanical Interests (via Gardener’s Supply Company, Hadley MA (retail store))' (8 rows, split, high)
--   originator 'Botanical Interests' via shop 'Gardener’s Supply Company'
UPDATE public.inventory_items t SET
       source_id = (SELECT s.id FROM public.source s
                     WHERE s.name = 'Botanical Interests' AND s.deleted_at IS NULL)
     , acquired_from_source_id = (SELECT s.id FROM public.source s
                                   WHERE s.name = 'Gardener’s Supply Company' AND s.deleted_at IS NULL)
 WHERE t.source = 'Botanical Interests (via Gardener’s Supply Company, Hadley MA (retail store))'
   AND t.source_id IS NULL;

-- inventory_items.source: 'Botanical Interests online order #350019 (confirmed 2026-07-08, received 2026-07-18); July 2026 intake.' (38 rows, merge, high)
UPDATE public.inventory_items t SET
       source_id = (SELECT s.id FROM public.source s
                     WHERE s.name = 'Botanical Interests' AND s.deleted_at IS NULL)
 WHERE t.source = 'Botanical Interests online order #350019 (confirmed 2026-07-08, received 2026-07-18); July 2026 intake.'
   AND t.source_id IS NULL;

-- inventory_items.source: 'Botanical Interests online order; captured 2026-06-10 as official seed->plant pipeline seeding' (89 rows, merge, high)
UPDATE public.inventory_items t SET
       source_id = (SELECT s.id FROM public.source s
                     WHERE s.name = 'Botanical Interests' AND s.deleted_at IS NULL)
 WHERE t.source = 'Botanical Interests online order; captured 2026-06-10 as official seed->plant pipeline seeding'
   AND t.source_id IS NULL;

-- inventory_items.source: 'Botanical Interests packet' (9 rows, merge, high)
UPDATE public.inventory_items t SET
       source_id = (SELECT s.id FROM public.source s
                     WHERE s.name = 'Botanical Interests' AND s.deleted_at IS NULL)
 WHERE t.source = 'Botanical Interests packet'
   AND t.source_id IS NULL;

-- inventory_items.source: 'Free from Belchertown Plant Swap, June 2026 (originally Lake Valley Seed, item #233)' (1 rows, split, high)
--   originator 'Lake Valley Seed' via shop 'Belchertown Plant Swap'
UPDATE public.inventory_items t SET
       source_id = (SELECT s.id FROM public.source s
                     WHERE s.name = 'Lake Valley Seed' AND s.deleted_at IS NULL)
     , acquired_from_source_id = (SELECT s.id FROM public.source s
                                   WHERE s.name = 'Belchertown Plant Swap' AND s.deleted_at IS NULL)
 WHERE t.source = 'Free from Belchertown Plant Swap, June 2026 (originally Lake Valley Seed, item #233)'
   AND t.source_id IS NULL;

-- inventory_items.source: 'Gardens at Mathews' (1 rows, merge, high)
UPDATE public.inventory_items t SET
       source_id = (SELECT s.id FROM public.source s
                     WHERE s.name = 'Own garden' AND s.deleted_at IS NULL)
 WHERE t.source = 'Gardens at Mathews'
   AND t.source_id IS NULL;

-- inventory_items.source: 'Greenfield Co-op' (2 rows, merge, high)
UPDATE public.inventory_items t SET
       source_id = (SELECT s.id FROM public.source s
                     WHERE s.name = 'Greenfield Farmers Co-op' AND s.deleted_at IS NULL)
 WHERE t.source = 'Greenfield Co-op'
   AND t.source_id IS NULL;

-- inventory_items.source: "Gurney's Seed & Nursery Co." (1 rows, new, high)
UPDATE public.inventory_items t SET
       source_id = (SELECT s.id FROM public.source s
                     WHERE s.name = 'Gurney''s Seed & Nursery Co.' AND s.deleted_at IS NULL)
 WHERE t.source = 'Gurney''s Seed & Nursery Co.'
   AND t.source_id IS NULL;

-- inventory_items.source: 'High Mowing Organic Seeds' (1 rows, new, high)
UPDATE public.inventory_items t SET
       source_id = (SELECT s.id FROM public.source s
                     WHERE s.name = 'High Mowing Organic Seeds' AND s.deleted_at IS NULL)
 WHERE t.source = 'High Mowing Organic Seeds'
   AND t.source_id IS NULL;

-- inventory_items.source: 'High Mowing Organic Seeds (via Gardener’s Supply Company, Hadley MA (retail store))' (1 rows, split, high)
--   originator 'High Mowing Organic Seeds' via shop 'Gardener’s Supply Company'
UPDATE public.inventory_items t SET
       source_id = (SELECT s.id FROM public.source s
                     WHERE s.name = 'High Mowing Organic Seeds' AND s.deleted_at IS NULL)
     , acquired_from_source_id = (SELECT s.id FROM public.source s
                                   WHERE s.name = 'Gardener’s Supply Company' AND s.deleted_at IS NULL)
 WHERE t.source = 'High Mowing Organic Seeds (via Gardener’s Supply Company, Hadley MA (retail store))'
   AND t.source_id IS NULL;

-- inventory_items.source: 'High Mowing packet' (2 rows, merge, high)
UPDATE public.inventory_items t SET
       source_id = (SELECT s.id FROM public.source s
                     WHERE s.name = 'High Mowing Organic Seeds' AND s.deleted_at IS NULL)
 WHERE t.source = 'High Mowing packet'
   AND t.source_id IS NULL;

-- inventory_items.source: 'Hillfolk Seed Collective' (2 rows, new, high)
UPDATE public.inventory_items t SET
       source_id = (SELECT s.id FROM public.source s
                     WHERE s.name = 'Hillfolk Seed Collective' AND s.deleted_at IS NULL)
 WHERE t.source = 'Hillfolk Seed Collective'
   AND t.source_id IS NULL;

-- inventory_items.source: 'Home Depot' (24 rows, new, high)
UPDATE public.inventory_items t SET
       source_id = (SELECT s.id FROM public.source s
                     WHERE s.name = 'Home Depot' AND s.deleted_at IS NULL)
 WHERE t.source = 'Home Depot'
   AND t.source_id IS NULL;

-- inventory_items.source: 'Home-saved (source not recorded)' (1 rows, merge, high)
UPDATE public.inventory_items t SET
       source_id = (SELECT s.id FROM public.source s
                     WHERE s.name = 'Own garden' AND s.deleted_at IS NULL)
 WHERE t.source = 'Home-saved (source not recorded)'
   AND t.source_id IS NULL;

-- inventory_items.source: "Jen's uncle" (1 rows, new, high)
UPDATE public.inventory_items t SET
       source_id = (SELECT s.id FROM public.source s
                     WHERE s.name = 'Jen''s uncle' AND s.deleted_at IS NULL)
 WHERE t.source = 'Jen''s uncle'
   AND t.source_id IS NULL;

-- inventory_items.source: "Johnny's Selected Seeds" (8 rows, new, high)
UPDATE public.inventory_items t SET
       source_id = (SELECT s.id FROM public.source s
                     WHERE s.name = 'Johnny''s Selected Seeds' AND s.deleted_at IS NULL)
 WHERE t.source = 'Johnny''s Selected Seeds'
   AND t.source_id IS NULL;

-- inventory_items.source: 'Livingston packet' (1 rows, new, high)
UPDATE public.inventory_items t SET
       source_id = (SELECT s.id FROM public.source s
                     WHERE s.name = 'Livingston Seed' AND s.deleted_at IS NULL)
 WHERE t.source = 'Livingston packet'
   AND t.source_id IS NULL;

-- inventory_items.source: 'Magic Wings Inc (via Belchertown Plant Swap)' (1 rows, split, high)
--   originator 'Magic Wings' via shop 'Belchertown Plant Swap'
UPDATE public.inventory_items t SET
       source_id = (SELECT s.id FROM public.source s
                     WHERE s.name = 'Magic Wings' AND s.deleted_at IS NULL)
     , acquired_from_source_id = (SELECT s.id FROM public.source s
                                   WHERE s.name = 'Belchertown Plant Swap' AND s.deleted_at IS NULL)
 WHERE t.source = 'Magic Wings Inc (via Belchertown Plant Swap)'
   AND t.source_id IS NULL;

-- inventory_items.source: "Mary's Heirloom Seeds online order (HOMESTEAD discount); July 2026 intake. Received 2026-07-17." (36 rows, merge, high)
UPDATE public.inventory_items t SET
       source_id = (SELECT s.id FROM public.source s
                     WHERE s.name = 'Mary''s Heirloom Seeds' AND s.deleted_at IS NULL)
 WHERE t.source = 'Mary''s Heirloom Seeds online order (HOMESTEAD discount); July 2026 intake. Received 2026-07-17.'
   AND t.source_id IS NULL;

-- inventory_items.source: 'Massachusetts Flower Growers Association' (1 rows, new, high)
UPDATE public.inventory_items t SET
       source_id = (SELECT s.id FROM public.source s
                     WHERE s.name = 'Massachusetts Flower Growers Association' AND s.deleted_at IS NULL)
 WHERE t.source = 'Massachusetts Flower Growers Association'
   AND t.source_id IS NULL;

-- inventory_items.source: 'Panorama Tours, Austria (souvenir)' (1 rows, new, medium)
UPDATE public.inventory_items t SET
       source_id = (SELECT s.id FROM public.source s
                     WHERE s.name = 'Panorama Tours' AND s.deleted_at IS NULL)
 WHERE t.source = 'Panorama Tours, Austria (souvenir)'
   AND t.source_id IS NULL;

-- inventory_items.source: 'Sandia Seed Company online order #152165; August 2026 intake.' (35 rows, merge, high)
UPDATE public.inventory_items t SET
       source_id = (SELECT s.id FROM public.source s
                     WHERE s.name = 'Sandia Seed Company' AND s.deleted_at IS NULL)
 WHERE t.source = 'Sandia Seed Company online order #152165; August 2026 intake.'
   AND t.source_id IS NULL;

-- inventory_items.source: 'Seed Savers Exchange (via Gardener’s Supply Company, Hadley MA (retail store))' (3 rows, split, high)
--   originator 'Seed Savers Exchange' via shop 'Gardener’s Supply Company'
UPDATE public.inventory_items t SET
       source_id = (SELECT s.id FROM public.source s
                     WHERE s.name = 'Seed Savers Exchange' AND s.deleted_at IS NULL)
     , acquired_from_source_id = (SELECT s.id FROM public.source s
                                   WHERE s.name = 'Gardener’s Supply Company' AND s.deleted_at IS NULL)
 WHERE t.source = 'Seed Savers Exchange (via Gardener’s Supply Company, Hadley MA (retail store))'
   AND t.source_id IS NULL;

-- inventory_items.source: 'Seed Savers Exchange packet' (3 rows, merge, high)
UPDATE public.inventory_items t SET
       source_id = (SELECT s.id FROM public.source s
                     WHERE s.name = 'Seed Savers Exchange' AND s.deleted_at IS NULL)
 WHERE t.source = 'Seed Savers Exchange packet'
   AND t.source_id IS NULL;

-- inventory_items.source: 'UMass Amherst Libraries - Common Seed Project' (1 rows, new, high)
UPDATE public.inventory_items t SET
       source_id = (SELECT s.id FROM public.source s
                     WHERE s.name = 'UMass Amherst Libraries Common Seed Project' AND s.deleted_at IS NULL)
 WHERE t.source = 'UMass Amherst Libraries - Common Seed Project'
   AND t.source_id IS NULL;

-- inventory_items.source: 'Walmart' (9 rows, new, high)
UPDATE public.inventory_items t SET
       source_id = (SELECT s.id FROM public.source s
                     WHERE s.name = 'Walmart' AND s.deleted_at IS NULL)
 WHERE t.source = 'Walmart'
   AND t.source_id IS NULL;

-- plants.source_ref: 'Amazon' (4 rows, merge, high)
UPDATE public.plants t SET
       source_id = (SELECT s.id FROM public.source s
                     WHERE s.name = 'Amazon' AND s.deleted_at IS NULL)
 WHERE t.source_ref = 'Amazon'
   AND t.source_id IS NULL;

-- plants.source_ref: 'Belchertown Plant Swap June' (1 rows, merge, high)
UPDATE public.plants t SET
       source_id = (SELECT s.id FROM public.source s
                     WHERE s.name = 'Belchertown Plant Swap' AND s.deleted_at IS NULL)
 WHERE t.source_ref = 'Belchertown Plant Swap June'
   AND t.source_id IS NULL;

-- plants.source_ref: 'Belchertown Plant Swap June 2026' (1 rows, merge, high)
UPDATE public.plants t SET
       source_id = (SELECT s.id FROM public.source s
                     WHERE s.name = 'Belchertown Plant Swap' AND s.deleted_at IS NULL)
 WHERE t.source_ref = 'Belchertown Plant Swap June 2026'
   AND t.source_id IS NULL;

-- plants.source_ref: 'Belchertown Plant swap June' (1 rows, merge, high)
UPDATE public.plants t SET
       source_id = (SELECT s.id FROM public.source s
                     WHERE s.name = 'Belchertown Plant Swap' AND s.deleted_at IS NULL)
 WHERE t.source_ref = 'Belchertown Plant swap June'
   AND t.source_id IS NULL;

-- plants.source_ref: 'Big Y sale' (2 rows, new, high)
UPDATE public.plants t SET
       source_id = (SELECT s.id FROM public.source s
                     WHERE s.name = 'Big Y' AND s.deleted_at IS NULL)
 WHERE t.source_ref = 'Big Y sale'
   AND t.source_id IS NULL;

-- plants.source_ref: 'Bonnie' (5 rows, split, high)
--   originator 'Bonnie Plants' via shop 'Home Depot'
UPDATE public.plants t SET
       source_id = (SELECT s.id FROM public.source s
                     WHERE s.name = 'Bonnie Plants' AND s.deleted_at IS NULL)
     , acquired_from_source_id = (SELECT s.id FROM public.source s
                                   WHERE s.name = 'Home Depot' AND s.deleted_at IS NULL)
 WHERE t.source_ref = 'Bonnie'
   AND t.source_id IS NULL;

-- plants.source_ref: 'Bostrom Farms' (2 rows, new, medium)
UPDATE public.plants t SET
       source_id = (SELECT s.id FROM public.source s
                     WHERE s.name = 'Bostrom Farms' AND s.deleted_at IS NULL)
 WHERE t.source_ref = 'Bostrom Farms'
   AND t.source_id IS NULL;

-- plants.source_ref: 'Botanical Interests' (31 rows, merge, high)
UPDATE public.plants t SET
       source_id = (SELECT s.id FROM public.source s
                     WHERE s.name = 'Botanical Interests' AND s.deleted_at IS NULL)
 WHERE t.source_ref = 'Botanical Interests'
   AND t.source_id IS NULL;

-- plants.source_ref: 'Burpee' (4 rows, new, high)
UPDATE public.plants t SET
       source_id = (SELECT s.id FROM public.source s
                     WHERE s.name = 'Burpee' AND s.deleted_at IS NULL)
 WHERE t.source_ref = 'Burpee'
   AND t.source_id IS NULL;

-- plants.source_ref: 'Chapley Gardens - 397 Greenfield Rd Deerfield MA' (3 rows, new, high)
UPDATE public.plants t SET
       source_id = (SELECT s.id FROM public.source s
                     WHERE s.name = 'Chapley Gardens' AND s.deleted_at IS NULL)
 WHERE t.source_ref = 'Chapley Gardens - 397 Greenfield Rd Deerfield MA'
   AND t.source_id IS NULL;

-- plants.source_ref: 'Class Grass Garden Canter' (1 rows, new, high)
UPDATE public.plants t SET
       source_id = (SELECT s.id FROM public.source s
                     WHERE s.name = 'Class Grass Garden Center' AND s.deleted_at IS NULL)
 WHERE t.source_ref = 'Class Grass Garden Canter'
   AND t.source_id IS NULL;

-- plants.source_ref: 'Emma Daley 2026.06.13' (1 rows, new, high)
UPDATE public.plants t SET
       source_id = (SELECT s.id FROM public.source s
                     WHERE s.name = 'Emma Daley' AND s.deleted_at IS NULL)
 WHERE t.source_ref = 'Emma Daley 2026.06.13'
   AND t.source_id IS NULL;

-- plants.source_ref: 'Greenfield Co-op' (3 rows, merge, high)
UPDATE public.plants t SET
       source_id = (SELECT s.id FROM public.source s
                     WHERE s.name = 'Greenfield Farmers Co-op' AND s.deleted_at IS NULL)
 WHERE t.source_ref = 'Greenfield Co-op'
   AND t.source_id IS NULL;

-- plants.source_ref: 'Greenfield Farmers Co-op' (1 rows, new, high)
UPDATE public.plants t SET
       source_id = (SELECT s.id FROM public.source s
                     WHERE s.name = 'Greenfield Farmers Co-op' AND s.deleted_at IS NULL)
 WHERE t.source_ref = 'Greenfield Farmers Co-op'
   AND t.source_id IS NULL;

-- plants.source_ref: 'Greenfield Farmers Market' (1 rows, new, high)
UPDATE public.plants t SET
       source_id = (SELECT s.id FROM public.source s
                     WHERE s.name = 'Greenfield Farmers Market' AND s.deleted_at IS NULL)
 WHERE t.source_ref = 'Greenfield Farmers Market'
   AND t.source_id IS NULL;

-- plants.source_ref: 'Hart Farm trust stand' (1 rows, new, high)
UPDATE public.plants t SET
       source_id = (SELECT s.id FROM public.source s
                     WHERE s.name = 'Hart Farm' AND s.deleted_at IS NULL)
 WHERE t.source_ref = 'Hart Farm trust stand'
   AND t.source_id IS NULL;

-- plants.source_ref: 'Hatfield Plant Swap' (1 rows, new, high)
UPDATE public.plants t SET
       source_id = (SELECT s.id FROM public.source s
                     WHERE s.name = 'Hatfield Plant Swap' AND s.deleted_at IS NULL)
 WHERE t.source_ref = 'Hatfield Plant Swap'
   AND t.source_id IS NULL;

-- plants.source_ref: 'Hatley Plant Swap' (1 rows, rename, high)
UPDATE public.plants t SET
       source_id = (SELECT s.id FROM public.source s
                     WHERE s.name = 'Hadley Plant Swap' AND s.deleted_at IS NULL)
 WHERE t.source_ref = 'Hatley Plant Swap'
   AND t.source_id IS NULL;

-- plants.source_ref: 'High Mowing Organic Seeds' (3 rows, merge, high)
UPDATE public.plants t SET
       source_id = (SELECT s.id FROM public.source s
                     WHERE s.name = 'High Mowing Organic Seeds' AND s.deleted_at IS NULL)
 WHERE t.source_ref = 'High Mowing Organic Seeds'
   AND t.source_id IS NULL;

-- plants.source_ref: 'Home Depot' (2 rows, merge, high)
UPDATE public.plants t SET
       source_id = (SELECT s.id FROM public.source s
                     WHERE s.name = 'Home Depot' AND s.deleted_at IS NULL)
 WHERE t.source_ref = 'Home Depot'
   AND t.source_id IS NULL;

-- plants.source_ref: 'Imogen' (3 rows, new, high)
UPDATE public.plants t SET
       source_id = (SELECT s.id FROM public.source s
                     WHERE s.name = 'Imogen' AND s.deleted_at IS NULL)
 WHERE t.source_ref = 'Imogen'
   AND t.source_id IS NULL;

-- plants.source_ref: 'Jen from Four Phantoms' (12 rows, split, high)
--   originator 'Jen' via shop 'Four Phantoms Brewing Company'
UPDATE public.plants t SET
       source_id = (SELECT s.id FROM public.source s
                     WHERE s.name = 'Jen' AND s.deleted_at IS NULL)
     , acquired_from_source_id = (SELECT s.id FROM public.source s
                                   WHERE s.name = 'Four Phantoms Brewing Company' AND s.deleted_at IS NULL)
 WHERE t.source_ref = 'Jen from Four Phantoms'
   AND t.source_id IS NULL;

-- plants.source_ref: 'Liz Young via Belchertown Plant Swap June' (1 rows, split, medium)
--   originator 'Liz Young' via shop 'Belchertown Plant Swap'
UPDATE public.plants t SET
       source_id = (SELECT s.id FROM public.source s
                     WHERE s.name = 'Liz Young' AND s.deleted_at IS NULL)
     , acquired_from_source_id = (SELECT s.id FROM public.source s
                                   WHERE s.name = 'Belchertown Plant Swap' AND s.deleted_at IS NULL)
 WHERE t.source_ref = 'Liz Young via Belchertown Plant Swap June'
   AND t.source_id IS NULL;

-- plants.source_ref: 'Long River' (1 rows, merge, high)
UPDATE public.plants t SET
       source_id = (SELECT s.id FROM public.source s
                     WHERE s.name = 'Long River Produce Market' AND s.deleted_at IS NULL)
 WHERE t.source_ref = 'Long River'
   AND t.source_id IS NULL;

-- plants.source_ref: 'Long River Market, Deerfield, MA, USA' (1 rows, merge, high)
UPDATE public.plants t SET
       source_id = (SELECT s.id FROM public.source s
                     WHERE s.name = 'Long River Produce Market' AND s.deleted_at IS NULL)
 WHERE t.source_ref = 'Long River Market, Deerfield, MA, USA'
   AND t.source_id IS NULL;

-- plants.source_ref: 'Long River Produce Market' (26 rows, new, high)
UPDATE public.plants t SET
       source_id = (SELECT s.id FROM public.source s
                     WHERE s.name = 'Long River Produce Market' AND s.deleted_at IS NULL)
 WHERE t.source_ref = 'Long River Produce Market'
   AND t.source_id IS NULL;

-- plants.source_ref: 'Nettlepoint Farm' (1 rows, new, medium)
UPDATE public.plants t SET
       source_id = (SELECT s.id FROM public.source s
                     WHERE s.name = 'Nettlepoint Farm' AND s.deleted_at IS NULL)
 WHERE t.source_ref = 'Nettlepoint Farm'
   AND t.source_id IS NULL;

-- plants.source_ref: 'Ojos de Luna' (4 rows, new, high)
UPDATE public.plants t SET
       source_id = (SELECT s.id FROM public.source s
                     WHERE s.name = 'Ojos de Luna' AND s.deleted_at IS NULL)
 WHERE t.source_ref = 'Ojos de Luna'
   AND t.source_id IS NULL;

-- plants.source_ref: "Renee's Garden" (2 rows, new, high)
UPDATE public.plants t SET
       source_id = (SELECT s.id FROM public.source s
                     WHERE s.name = 'Renee''s Garden' AND s.deleted_at IS NULL)
 WHERE t.source_ref = 'Renee''s Garden'
   AND t.source_id IS NULL;

-- plants.source_ref: 'Seed Savers Exchange' (1 rows, merge, high)
UPDATE public.plants t SET
       source_id = (SELECT s.id FROM public.source s
                     WHERE s.name = 'Seed Savers Exchange' AND s.deleted_at IS NULL)
 WHERE t.source_ref = 'Seed Savers Exchange'
   AND t.source_id IS NULL;

-- plants.source_ref: 'Shawski Farm' (1 rows, merge, high)
UPDATE public.plants t SET
       source_id = (SELECT s.id FROM public.source s
                     WHERE s.name = 'Skawski Farms' AND s.deleted_at IS NULL)
 WHERE t.source_ref = 'Shawski Farm'
   AND t.source_id IS NULL;

-- plants.source_ref: 'Shawski Farms' (2 rows, merge, high)
UPDATE public.plants t SET
       source_id = (SELECT s.id FROM public.source s
                     WHERE s.name = 'Skawski Farms' AND s.deleted_at IS NULL)
 WHERE t.source_ref = 'Shawski Farms'
   AND t.source_id IS NULL;

-- plants.source_ref: 'Skawski Farms' (1 rows, new, high)
UPDATE public.plants t SET
       source_id = (SELECT s.id FROM public.source s
                     WHERE s.name = 'Skawski Farms' AND s.deleted_at IS NULL)
 WHERE t.source_ref = 'Skawski Farms'
   AND t.source_id IS NULL;

-- plants.source_ref: 'Starview' (2 rows, merge, high)
UPDATE public.plants t SET
       source_id = (SELECT s.id FROM public.source s
                     WHERE s.name = 'Starview Gardens' AND s.deleted_at IS NULL)
 WHERE t.source_ref = 'Starview'
   AND t.source_id IS NULL;

-- plants.source_ref: 'Starview Gardens' (46 rows, new, high)
UPDATE public.plants t SET
       source_id = (SELECT s.id FROM public.source s
                     WHERE s.name = 'Starview Gardens' AND s.deleted_at IS NULL)
 WHERE t.source_ref = 'Starview Gardens'
   AND t.source_id IS NULL;

-- plants.source_ref: 'Sunderland - trust stand' (1 rows, new, high)
UPDATE public.plants t SET
       source_id = (SELECT s.id FROM public.source s
                     WHERE s.name = 'Sunderland trust stand' AND s.deleted_at IS NULL)
 WHERE t.source_ref = 'Sunderland - trust stand'
   AND t.source_id IS NULL;

-- plants.source_ref: 'The Warren Place Flower Farm' (1 rows, new, high)
UPDATE public.plants t SET
       source_id = (SELECT s.id FROM public.source s
                     WHERE s.name = 'The Warren Place Flower Farm' AND s.deleted_at IS NULL)
 WHERE t.source_ref = 'The Warren Place Flower Farm'
   AND t.source_id IS NULL;

-- plants.source_ref: 'Trust Stand Greenfield -Upper Road' (1 rows, new, high)
UPDATE public.plants t SET
       source_id = (SELECT s.id FROM public.source s
                     WHERE s.name = 'Trust stand, Upper Road' AND s.deleted_at IS NULL)
 WHERE t.source_ref = 'Trust Stand Greenfield -Upper Road'
   AND t.source_id IS NULL;

-- plants.source_ref: 'Trust stand in Hadley' (1 rows, new, high)
UPDATE public.plants t SET
       source_id = (SELECT s.id FROM public.source s
                     WHERE s.name = 'Trust stand, Hadley' AND s.deleted_at IS NULL)
 WHERE t.source_ref = 'Trust stand in Hadley'
   AND t.source_id IS NULL;

-- plants.source_ref: 'Whatley Giving Garden' (1 rows, merge, high)
UPDATE public.plants t SET
       source_id = (SELECT s.id FROM public.source s
                     WHERE s.name = 'Whately Plant Swap' AND s.deleted_at IS NULL)
 WHERE t.source_ref = 'Whatley Giving Garden'
   AND t.source_id IS NULL;

-- plants.source_ref: 'Whatley Plant Swap' (4 rows, new, high)
UPDATE public.plants t SET
       source_id = (SELECT s.id FROM public.source s
                     WHERE s.name = 'Whately Plant Swap' AND s.deleted_at IS NULL)
 WHERE t.source_ref = 'Whatley Plant Swap'
   AND t.source_id IS NULL;

-- ── 3. RECEIPT ───────────────────────────────────────────────────────────────────────────
INSERT INTO public.schema_version (version, description, applied_at)
VALUES ('5.0.0-sourcebackfill-001',
        'SOURCEBACKFILL: V5-SOURCEBACKFILL-001. Populates public.source with 53 reviewed '
        'catalogue rows plus the V5-SOURCEUNKNOWN-001 Unknown row, then sets source_id and '
        'acquired_from_source_id on plants and inventory_items from the 74 reviewed '
        'spellings. plants.source_ref and inventory_items.source are READ ONLY and remain '
        'the record of provenance; every UPDATE is IS NULL-guarded so a re-run cannot '
        'overwrite a human correction. Fully reversible by nulling the four FK columns '
        '(0r-rollback.sql). Dave approved the run 2026-09-04 with five medium-confidence '
        'kind labels named to him.',
        now())
ON CONFLICT (version) DO UPDATE
  SET applied_at = now(), description = EXCLUDED.description;

COMMIT;
