-- 0d-seed-samples.sql — GENERATED by scripts/cal1/gen-cal1-seed.mjs from src/data/harvest-weights-v2.json
-- Batch: 20260803-dave-tomato. Fail-CLOSED keying (insert only if EXACTLY ONE live cultivar matches
-- (crop_type_slug, display_name)) + batch-idempotent (re-applying this batch does not double-insert).
-- Depends on v4-cal1-pervariety-001/0a. Dave-gated apply. Run 0d-coverage.sql to see key resolution.

INSERT INTO public.cultivar_weight_sample (cultivar_id, unit, total_grams, unit_count, sampled_at, seed_batch, note, created_by)
SELECT m.id, v.unit, v.total_grams, v.unit_count, v.sampled_at, '20260803-dave-tomato', v.note, 'cal1-seed'
FROM (VALUES
  ('tomato', 'San Marzano Roma', 'count', 337::numeric, 5::numeric, '2026-08-03'::timestamptz, 'Dave: ''5 tomatoes were 337g total''. Reported as ''San Marzano''; the only San Marzano PLANTING is San Marzano Roma, so the same derived value was applied to both varieties.'),
  ('tomato', 'San Marzano', 'count', 337::numeric, 5::numeric, '2026-08-03'::timestamptz, 'SAME physical weighing as the San Marzano Roma row — recorded against both variety rows because Dave reported it as ''San Marzano'' and the DB carries both names. Not an independent sample; do NOT treat the pair as n=2.'),
  ('tomato', 'Moskvich Heirloom', 'count', 115::numeric, 1::numeric, '2026-08-03'::timestamptz, 'Dave: ''115g each — a very good representative size here''.'),
  ('tomato', 'Super Sweet 100', 'count', 8::numeric, 1::numeric, '2026-08-03'::timestamptz, 'Dave: ''8g each''.'),
  ('tomato', 'Black Cherry', 'count', 16::numeric, 1::numeric, '2026-08-03'::timestamptz, 'Dave: ''16g each''.'),
  ('tomato', 'Cherry Falls', 'count', 74::numeric, 12::numeric, '2026-08-03'::timestamptz, 'Dave: ''12 tomatoes were 74g total''.'),
  ('tomato', 'Sunray', 'count', 90::numeric, 1::numeric, '2026-08-03'::timestamptz, 'Dave: ''90g each''.'),
  ('tomato', 'Celebrity', 'count', 273::numeric, 3::numeric, '2026-08-03'::timestamptz, 'Dave: ''273g for 3 total''.'),
  ('tomato', 'Granadero', 'count', 168::numeric, 2::numeric, '2026-08-03'::timestamptz, 'Dave: ''168g for 2 total'' (reported as ''grandadero'').')
) AS v(slug, name, unit, total_grams, unit_count, sampled_at, note)
JOIN LATERAL (
  SELECT c.id FROM public.cultivar c
   WHERE c.crop_type_slug = v.slug AND c.display_name = v.name AND c.deleted_at IS NULL
) m ON true
WHERE (SELECT count(*) FROM public.cultivar c2
        WHERE c2.crop_type_slug = v.slug AND c2.display_name = v.name AND c2.deleted_at IS NULL) = 1
  AND NOT EXISTS (
    SELECT 1 FROM public.cultivar_weight_sample s
     WHERE s.seed_batch = '20260803-dave-tomato' AND s.cultivar_id = m.id AND s.unit = v.unit
       AND s.sampled_at = v.sampled_at AND s.total_grams = v.total_grams AND s.unit_count = v.unit_count
  );
