#!/usr/bin/env python3
"""Freeze ci.yml's `build-and-test` job as a manifest: every step's WHOLE mapping, in order.

WHY THIS EXISTS. `build-and-test` is one serial job of 44 steps and it is about to be split into parallel legs.
A step that is dropped, reordered, given an `if:` or handed a different `env` in that move would still leave a
green check. This manifest is the conservation instrument: what the job runs today, written down, so that the
split (and every CI edit before it) can be compared against it step for step.

It is a moving file, not a freeze on CI. A lane that adds or edits a step re-runs this script and commits the new
manifest in the same commit; scripts/test_ci_step_manifest.py fails until it does.

WHAT IS RECORDED. Per step: name, uses, with, run, env, shell, working-directory (null when the step has no such
key), and under `other` any key not in that list, so nothing a step carries can go unrecorded. `run` is the exact
body as a list of its lines (joined with "\n" it is the string the runner executes), which keeps diffs and merges
line-sized. Per job: runs-on, env and any other key except `steps`. Per workflow: env and defaults, because both
change what every step runs with. YAML comments are not part of any of these; a shell comment inside a `run:`
body is.

`timeout-minutes` on the job is recorded under `informational` and NOT compared: it bounds the job without
changing what a step does, so adding or changing it needs no manifest update.

Run: python3 scripts/gen-ci-step-manifest.py            rewrite scripts/ci-step-manifest.json
     python3 scripts/gen-ci-step-manifest.py --check    exit 1 if ci.yml and the manifest disagree
"""
import json
import os
import sys

import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WORKFLOW = ".github/workflows/ci.yml"
JOB = "build-and-test"
MANIFEST = "scripts/ci-step-manifest.json"
STEP_KEYS = ("name", "uses", "with", "run", "env", "shell", "working-directory")
JOB_KEYS = ("runs-on", "env")
WORKFLOW_KEYS = ("env", "defaults")
INFORMATIONAL = ("timeout-minutes",)
UNPINNED = ("_about", "informational")
CHANGED = ("ci.yml build-and-test changed: run scripts/gen-ci-step-manifest.py and commit the manifest in the "
           "same commit")
ABOUT = ("Generated by scripts/gen-ci-step-manifest.py from %s; do not edit by hand. A step's `run` is its exact "
         "body, one list item per line. `informational` is recorded and not compared." % WORKFLOW)


def load_workflow(root=ROOT):
    with open(os.path.join(root, WORKFLOW), encoding="utf-8") as fh:
        return yaml.safe_load(fh)


def _step(step):
    out = {key: step.get(key) for key in STEP_KEYS}
    if out["run"] is not None:
        out["run"] = str(out["run"]).split("\n")
    out["other"] = {str(key): value for key, value in step.items() if key not in STEP_KEYS}
    return out


def build(workflow):
    """The manifest for a parsed ci.yml."""
    job = workflow["jobs"][JOB]
    skip = JOB_KEYS + INFORMATIONAL + ("steps",)
    return {
        "_about": ABOUT,
        "workflow": WORKFLOW,
        "job": JOB,
        "workflow_keys": {key: workflow.get(key) for key in WORKFLOW_KEYS},
        "job_keys": dict({key: job.get(key) for key in JOB_KEYS},
                         other={str(key): value for key, value in job.items() if key not in skip}),
        "informational": {key: job.get(key) for key in INFORMATIONAL},
        "steps": [_step(step) for step in job["steps"]],
    }


def render(manifest):
    """The one byte form of a manifest: sorted keys, two-space indent, UTF-8 as written, LF, trailing newline."""
    return json.dumps(manifest, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


def _label(index, step):
    return "step %d (%s)" % (index + 1, step.get("name") or step.get("uses") or "unnamed")


def differences(committed, current):
    """What differs between two manifests, one line each; [] when the pinned parts are equal."""
    out = []
    for key in sorted((set(committed) | set(current)) - set(UNPINNED) - {"steps"}):
        if committed.get(key) != current.get(key):
            out.append("%s: manifest %s, ci.yml %s" % (key, json.dumps(committed.get(key), sort_keys=True),
                                                       json.dumps(current.get(key), sort_keys=True)))
    was, now = committed.get("steps") or [], current.get("steps") or []
    if len(was) != len(now):
        out.append("step count: manifest %d, ci.yml %d" % (len(was), len(now)))
    for index, (old, new) in enumerate(zip(was, now)):
        keys = sorted(key for key in set(old) | set(new) if old.get(key) != new.get(key))
        if keys:
            out.append("%s: %s differ%s" % (_label(index, new), ", ".join(keys), "s" if len(keys) == 1 else ""))
    for index in range(len(now), len(was)):
        out.append("%s: in the manifest, not in ci.yml" % _label(index, was[index]))
    for index in range(len(was), len(now)):
        out.append("%s: in ci.yml, not in the manifest" % _label(index, now[index]))
    return out


def main(argv=None):
    argv = sys.argv[1:] if argv is None else argv
    if argv not in ([], ["--check"]):
        sys.stderr.write(__doc__)
        return 2
    path = os.path.join(ROOT, MANIFEST)
    current = build(load_workflow())
    if argv == ["--check"]:
        with open(path, encoding="utf-8") as fh:
            found = differences(json.load(fh), current)
        if found:
            sys.stderr.write(CHANGED + "\n" + "".join("  %s\n" % line for line in found))
            return 1
        print("%s matches %s (%d steps)" % (MANIFEST, WORKFLOW, len(current["steps"])))
        return 0
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(render(current))
    print("wrote %s: %d steps of %s job %s" % (MANIFEST, len(current["steps"]), WORKFLOW, JOB))
    return 0


if __name__ == "__main__":
    sys.exit(main())
