// v2wire.js — the Today V2 states' wire and device state, for the harness entries (todaymeasure ?v2=1 and
// todayshell). V5-TODAYREDESIGN-001 S0.
//
// PURE FUNCTIONS ONLY: nothing here touches window at import, so the node side (the grafts' unit test) can
// import it too. The entries call them; the state table they read is today-v2-contract.mjs, and the graft
// data is v2-grafts.json (GENERATED by build-v2-grafts.mjs through the engine's own functions).
//
// Every transform here MOVES a field of a real payload and never invents a row; the one synthetic payload
// (the freeze state's bring_in cards) is labelled synthetic in v2-grafts.json, where it was produced.

const withPlan = (payload, fn) => (payload && payload.plan ? { ...payload, plan: fn(payload.plan) } : payload)
const DAY_MS = 86400000

// The parameterised re-dating helper (plan §8 S0): serve `payload` dated `day` (YYYY-MM-DD). generated_at
// moves by the same whole number of days, so the "as of" stamp keeps its time of day and describes the
// morning the clock is pinned to — the storage state's +7 days, generalised.
export function redatePayload(payload, day) {
  if (!payload || !day) return payload
  if (!/^\d{4}-\d{2}-\d{2}$/.test(day)) throw new Error(`redatePayload: '${day}' is not YYYY-MM-DD`)
  const from = payload.plan_date
  const shift = from ? Date.parse(`${day}T12:00:00.000Z`) - Date.parse(`${from}T12:00:00.000Z`) : 0
  const gen = payload.generated_at ? new Date(Date.parse(payload.generated_at) + shift).toISOString() : payload.generated_at
  return { ...payload, plan_date: day, generated_at: gen }
}

// Apply the named grafts, in order, to a state's plan payload and its /api/plants list.
export function applyGrafts(payload, plants, names, G) {
  let p = payload
  let pl = plants
  for (const n of names || []) {
    const g = G && G[n]
    if (!g) throw new Error(`unknown graft '${n}' — v2-grafts.json has ${Object.keys(G || {}).filter((k) => k !== '_' && k !== 'base').join(', ')}`)
    if (n === 'routine') {
      pl = pl.map((x) => (g.plants_container_type[x.id] ? { ...x, container_type: g.plants_container_type[x.id] } : x))
    } else if (n === 'hot') {
      p = withPlan(p, (plan) => ({ ...plan, weather: { ...(plan.weather || {}), ...g.weather } }))
    } else if (n === 'never') {
      p = withPlan(p, (plan) => {
        const water_due = plan.water_due.filter((r) => r.id !== g.move_to_no_history)
        if (water_due.length !== plan.water_due.length - 1) throw new Error(`graft never: row ${g.move_to_no_history} is not in water_due`)
        const no_history = [...(plan.no_history || []), g.row]
        return { ...plan, water_due, no_history, counts: { ...(plan.counts || {}), water_due: water_due.length, no_history: no_history.length } }
      })
    } else if (n === 'bedwait') {
      p = withPlan(p, (plan) => {
        const moved = new Set(g.move_to_rain_skipped)
        const water_due = plan.water_due.filter((r) => !moved.has(r.id))
        if (plan.water_due.length - water_due.length !== moved.size) throw new Error('graft bedwait: a deferred bed is not in water_due')
        const rain_skipped = [...(plan.rain_skipped || []), ...g.rain_skipped_rows]
        return {
          ...plan, water_due, rain_skipped,
          hydrology: { ...(plan.hydrology || {}), ...g.hydrology },
          counts: { ...(plan.counts || {}), water_due: water_due.length, rain_skipped: rain_skipped.length },
        }
      })
    } else if (n === 'freeze') {
      p = withPlan(p, (plan) => {
        const reworded = (plan.cold || []).map((c) => ({ ...c, text: String(c.text || '').split(g.cold_reword.from).join(g.cold_reword.to) }))
        const cold = [...reworded, ...g.cold_add]
        return { ...plan, cold, weather: { ...(plan.weather || {}), ...g.weather }, counts: { ...(plan.counts || {}), cold: cold.length } }
      })
    } else if (n === 'stale') {
      p = redatePayload(p, g.plan_date)
    } else {
      throw new Error(`graft '${n}' has no applier in v2wire.js`)
    }
  }
  return { payload: p, plants: pl }
}

// Device state for a state, written BEFORE mount. Returns the entries to write (the entry writes them), so
// this stays pure: [key, value] pairs. `userId` is the harness Clerk stub's id.
export function localSeeds(state, payload, userId) {
  const out = [['garden.todayV2', '1']]
  const L = state.local || {}
  if (L.todaySeen) {
    const chill = {}
    for (const c of (payload && payload.plan && payload.plan.cold) || []) chill[String(c.id).slice(0, 8)] = L.todaySeen.date
    out.push([`today-seen:${userId}`, JSON.stringify({ season: '2026-autumn', chill })])
  }
  if (L.mirror) out.push([`today-sections:${userId}`, JSON.stringify({ v: 1, s: L.mirror, dirty: [] })])
  if (L.showOthers) out.push(['garden.today.showOthers', '1'])
  return out
}

// The day a state's clock names (YYYY-MM-DD in ET — every contract clock is 14:30Z = 10:30 ET).
export const dayOfClock = (iso) => String(iso || '').slice(0, 10)

// Build a v2 state's wire: the plan payload, the plants list and the prefs body, from the v1 payload the
// state starts from. `base` = { payload, plants } for state.fixture, as the entry's v1 machinery built it.
export function buildV2State(state, base, G, prefsBody) {
  let payload = base.payload
  let plants = base.plants
  if (state.redate) payload = redatePayload(payload, state.redate)
  ;({ payload, plants } = applyGrafts(payload, plants, state.grafts, G))
  return { payload, plants, prefs: prefsBody, prefsDelayMs: state.prefsDelayMs || 0 }
}

// The interaction driver's target resolution (plan §8 S0 seam c). A step names its target in the contract's
// vocabulary; this turns it into a selector against the anchor conventions (today-v2-contract.mjs ANCHORS).
//   jump:<chip>          a jump-bar chip:        [data-testid="today-jumpbar"] [data-chip="<chip>"]
//   section:<key>        a section header:       [data-testid="today-sec-<key>"] [aria-expanded]
//   spot:<name>          a spot's toggle:        [data-testid="care-spot"][data-spot="<name>"] [aria-expanded]
//   cohort:<name>        a spot's cohort toggle: [data-testid="care-cohort"][data-spot="<name>"] [aria-expanded]
//   glance               the glance card's toggle: [data-testid="today-glance"] [aria-expanded]
//   testid:<id>          anything else by testid
// `flip` names the element whose aria-expanded must change, in the same vocabulary (a bare
// `today-sec-<key>` / `care-spot:<name>` / `care-cohort:<name>`).
export function selectorFor(target, suffix = '') {
  const [kind, ...rest] = String(target).split(':')
  const arg = rest.join(':')
  const q = (s) => s.replace(/"/g, '\\"')
  switch (kind) {
    case 'jump': return `[data-testid="today-jumpbar${suffix}"] [data-chip="${q(arg)}"]`
    case 'section': return `[data-testid="today-sec-${q(arg)}${suffix}"] [aria-expanded]`
    case 'spot': return `[data-testid="care-spot${suffix}"][data-spot="${q(arg)}"] [aria-expanded]`
    case 'cohort': return `[data-testid="care-cohort${suffix}"][data-spot="${q(arg)}"] [aria-expanded]`
    case 'care-spot': return `[data-testid="care-spot${suffix}"][data-spot="${q(arg)}"] [aria-expanded]`
    case 'care-cohort': return `[data-testid="care-cohort${suffix}"][data-spot="${q(arg)}"] [aria-expanded]`
    case 'testid': return `[data-testid="${q(arg)}${suffix}"]`
    case 'glance': return `[data-testid="today-glance${suffix}"] [aria-expanded]`
    default:
      if (kind.startsWith('today-sec-')) return `[data-testid="${q(kind)}${suffix}"] [aria-expanded]`
      throw new Error(`selectorFor: unknown target '${target}'`)
  }
}
